### ISSUE TITLE
Clean git repo being incorrectly reported as dirty by Powerline

### ISSUE THREAD

**Issue by stephenhowells** [powerline/powerline#1107]
I have one directory where Powerline is convinced the git repo is dirty. I double check and my git status indicates there is nothing to stage or commit. This only occurs for this one git repo. Is there a cahce of some kind that I can clear out so that Powerline reports the correct git status? I'm on OS X 10.9.5.

**Comment by jsjohnst** [comment]
@stephenhowells I had a similar issue and finally tracked it down. The issue is that Powerline shows a git repo as dirty when there are ignored files. I can't fathom why if something was explicitly ignored by a .gitignore, why I would want to have it be not ignored, but alas, this was obviously intended reading the code.
