### ISSUE TITLE
U+231a Glyph

### ISSUE THREAD

**Issue by rfkortekaas** [powerline/powerline#1243]
I'm using powerline with tmux and URxvt, but the U+231a Glyph doesn't show (Watch symbol) for the time. After struggling a lot with the powerline font I found out that the Glyph is not available in the Liberation Mono font, and also all the other Patched powerline fonts. When using XFCE4-terminal it displays the watch, but apparently this is using some fallback font. Which font should work correctly for this?

**Comment by ZyX-I** [comment]
No idea. In any case it is not an issue and thus should not be posted to the issue tracker.

If you need to check whether specific glyph is in specific font you can use

    import fontforge
    font = fontforge.open('/path/to/font')
    font[0x231A]

. If this raises an exception then glyph is not in a font. This method is guaranteed not to use any fallback fonts and if moved to a script is the most fast and reliable method I know (I know only one). I would suggest to open issue in fontpatcher bug tracker asking to add missing glyphs *not* to private use area because powerline uses a number of glyphs that are rarely present in monospace fonts.

I think if fontpatcher is not modified it makes sense to combine `powerline` and `unicode_terminus` top-level themes and make the result the default one (finst is the current default, second theme contains only characters found in terminus PCF font (PCF is essential: there is terminus font for /dev/ttyN kernel terminal emulators)).
