### ISSUE TITLE
Terminal title changed to default profile

### ISSUE THREAD

**Issue by tubia** [powerline/powerline#1262]
Hi,
I'm using `gnome-terminal` in Linux Min 17.
Was able to install powerline system-wide and it works, after configuring `.bashrc` but actually the title of the terminal returns to the default title profile which is, in my case, "Terminal".  
I tried to put in `.bashrc`:
```
PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
```
To restore normal usage, but it breaks the powerline configuration.

**Comment by ZyX-I** [comment]
I do not understand what this issue is about.

**Comment by tubia** [comment]
I accidentally pressed `Return` key. Sorry for that.

**Comment by ZyX-I** [comment]
@tubia You need to put `PROMPT_COMMAND` *before* sourcing powerline bindings (powerline should preserve existing code found in this variable). Or check out powerline bindings and use the same code for *appending* to prompt command. In any case you must not *set* this variable, append to it.

Though better just use zsh.

**Comment by ZyX-I** [comment]
To append you need something like

    PROMPT_COMMAND="${PROMPT_COMMAND"$'\necho -n "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'

**Comment by tubia** [comment]
Thank you for the fast reply @ZyX-I  
I added exactly this line in the `.bashrc`, but now before sourcing powerline
```
# added powerline
PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
if [ -f /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh ]; then
    source /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh
fi
```
Now it works, it shows "Terminal" title for an half of a second when opening a new terminal and then it shows `$user : $hostname` as it should.  
Yep, I definitely need to switch to *zsh* :)

**Comment by ZyX-I** [comment]
@tubia Zsh has an array of functions which naturally is appended to:

    your_prompt_command() {
        echo -n "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
    }
    precmd_functions+=( your_prompt_command )

in place of prompt command, but to display powerline this functionality is not needed because I can just use `PSn='$(…)'` (in bash this variant has issues with determining length of the prompt, so I have to set PSn from PROMPT_COMMAND which also results in continuation prompts limitations). (I still use this functionality though, but only for computing some additional values I cannot compute in a subshell.)

Regarding powerline you may get in zsh:

1. Right-side prompt.
2. Anything you want in continuation prompt. By default it shows “parser state” there: e.g. `echo '<CR>` will show continuation prompt with `quote` in it. Bash does not provide this functionality.
3. If you are using Vi-style keyboard bindings powerline may show you current mode. I have no idea how to do this in bash.
4. Anything you want in select prompt (in bash I *have* to compute continuation, select and regular prompt at once which obviously affects both performance (not too much with powerline-daemon) and punctuality of information).

**Comment by mvdberge** [comment]
To get the relative path (e.g. ~ for your home directory) use the following before sourcing the powerline.sh:
`PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: $(dirs +0)\007"'`

**Comment by Shulyaka** [comment]
> To get the relative path (e.g. ~ for your home directory) use the following before sourcing the powerline.sh:
> 
> `PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: $(dirs +0)\007"'`

This should be added to the documentation
