### ISSUE TITLE
Bash Prompt: readline insert/normal mode

### ISSUE THREAD

**Issue by orbisvicis** [powerline/powerline#1291]
It would be great if the bash prompt would change color just as the vim one does.

What has to be done / is it easy ?

**Comment by ZyX-I** [comment]
And you, of course, know how to do this? I do not. Pull requests are welcome.

**Comment by ZyX-I** [comment]
Fish and zsh provide environment variables that are accessible either always (fish) or in zle widgets (zsh) that can show you the current mode. Bash is using readline for this and hence is rather not configurable; and it is not providing any access to readline state I know about.

**Comment by ZyX-I** [comment]
This (readline) is also the reason bash does not have support for right prompt.

**Comment by petobens** [comment]
Hi @ZyX-I, can this [new bash feature](http://stackoverflow.com/a/17144421/2149400) be used to capture the readline state?

**Comment by ZyX-I** [comment]
@petobens How? It directs readline to show mode *in prompt*, powerline can get it from there only (assuming no root access) by being a proxy between bash and terminal emulator. I am not going to write something like this.

**Comment by petobens** [comment]
@ZyX-I ok, thanks for the explanation.

**Comment by scde** [comment]
@ZyX-I & @petobens Just a heads-up as mentioned in the SO-thread: ["Bash 4.4 / Readline 7.0 will add support for user-settable mode strings."](http://stackoverflow.com/a/33338607) (and it has [released](https://cnswww.cns.cwru.edu/php/chet/readline/CHANGES) since and is for example available in Ubuntu 17.04)

So there is the possibility to enable showing ins-/cmd-mode indicators with `set show-mode-in-prompt on` (.inputrc) and customize it with something along the lines of:
```
set vi-ins-mode-string \1\e[48;5;117;1m\2 I \1\e[38;5;117;48;5;31;1m\2\1\e[0m\2
set vi-cmd-mode-string \1\e[48;5;166;1m\2 N \1\e[38;5;166;48;5;31;1m\2\1\e[0m\2
```
I think there is also 'emacs-mode-string'. Anyway it kind of works (or integrates better) but I was not able to properly match powerline.

![before_after](https://cloud.githubusercontent.com/assets/16360982/24966289/cde3cc3c-1fa6-11e7-9917-9dabc9ac5752.png)
(left without and right with the string)

**Comment by petobens** [comment]
@scde this is awesome! I hope it can be intregrated smoothly to powerline in the near future.

**Comment by ZyX-I** [comment]
The string like this cannot be a powerline segment, it does not provide any data accessible for the powerline. Would be much like another pseudo-segments already raising a number of issues “I do not find a way to configure” and “segment behaviour is unexpected and does not match real powerline segments” which powerline has in tmux. Note that the color of the segment after the mode pseudo-segment may and will change, you can’t possibly match that by modifying inputrc, that is available only after computing PS1 in $PROMPT_COMMAND.
