### ISSUE TITLE
Is multi-user powerline-daemon possible?

### ISSUE THREAD

**Issue by ShiroiKuma** [powerline/powerline#1303]
This is more of a question than an issue as I have a work around. Is it possible to get ```powerline-daemon``` to run once and have all users access it?

I run several users on my servers and I like to have powerline as it really helps. However if I login as ```user1``` and then run ```powerline-daemon -q``` if I su to user2 I notice it's using the script version due to the slow down.

At the moment I've got a script doing <pre><code>sudo user1 powerline-daemon -q
sudo user2 powerline-daemon -q
sudo user3 powerline-daemon -q</code></pre>

Which while it works, it seems a waste of resources to do so. Is this the only way or is there a better way?

**Comment by ZyX-I** [comment]
This is going to have either permission or security problems. I.e. you either run it as root and it has access to anything, but is now a possible security hole or run it as some user, but you only have access to whatever user has access to (meaning that it is no longer able to query status of some repositories, but will spam errors regarding them).

There actually is a way to do so, but some segments in daemon are using daemon’s process user ID as their data, so running `powerline-daemon --socket /tmp/all-user-socket` is not going to work properly (`--socket` argument was created for tests). To use this socket in shells you need to set `POWERLINE_COMMAND_ARGS='--socket /tmp/all-user-socket`, but note that this functionality is said to be for tests only and thus is subject for changes at any time I want (i.e. without triggering major version update).

I see not much problems with multiple instances of `powerline-daemon` because of time it is in `Sl` state (`l` is there only if you use some segments like weather one, most of time all threads are waiting for events as well).

**Comment by ShiroiKuma** [comment]
Thanks for the explanation. Really appreciate the help today. This is really a fantastic shell extension and I'm really grateful to have consistent/informative and helpful prompts on all my systems from Gentoo/CentOS to even Windows/Cygwin. Kudos man!
