### ISSUE TITLE
Mail segment not working in wm theme due to colorscheme problems

### ISSUE THREAD

**Issue by fradeve** [powerline/powerline#1320]
* OS: Archlinux
* Powerline: [python-powerline-git](https://aur.archlinux.org/packages/python-powerline-git)
* version: 2.1 (ca6797055a728bb043d0ac46a849949d8efd72ff)

I'm using the mail segment with LemonBoy's [Bar](https://github.com/LemonBoy/bar) (compiled on the ``cairo-love`` branch):
``/home/fradeve/.config/powerline/config.json``

```json
    }
    "ext": {
        "wm": {
            "colorscheme": "default",
             "theme": "fradeve"
        }
    }
```

``/home/fradeve/.config/powerline/themes/wm/fradeve.json``
```json
        "email_imap_alert": {
                "before": "✉ ",
                "args": {
                    "server" : "mail.some.org",
                    "username": "francesco.devirgilio@inventati.org",
                    "password": ""
                }
           }
```
``/home/fradeve/.i3/config``
```bash
exec python /usr/lib/python3.4/site-packages/powerline/bindings/bar/powerline-bar.py --i3 | bar -b -f "-misc-dejavu sans mono-medium-r-normal--11-*-*-*-m-*-iso10646-1"
```
It works perfectly inside Tmux bar, but it errors in wm, due to the lack of a colorscheme (the error flicks for just 1 sec on the bar, so I'm not able to copy/paste it here, but it has to do with the lack of "groups" in ``email_alert`` or something similar).
The segment works if I create ``/home/fradeve/.config/powerline/colorschemes/wm/default.json`` with this content:
```json
{
	"name": "Default color scheme for window managers",
	"groups": {
		"background:divider": { "fg": "gray5", "bg": "gray0" },
		"session": { "fg": "black", "bg": "gray10", "attr": ["bold"] },
		"date": { "fg": "gray8", "bg": "gray2" },
		"time": { "fg": "gray10", "bg": "gray2", "attr": ["bold"] },
		"time:divider": { "fg": "gray5", "bg": "gray2" },
		"email_alert": { "fg": "white", "bg": "brightred", "attr": ["bold"] },
		"email_alert_gradient": { "fg": "white", "bg": "yellow_orange_red", "attr": ["bold"] },
		"hostname": { "fg": "black", "bg": "gray10", "attr": ["bold"] },
		"weather": { "fg": "gray8", "bg": "gray0" },
		"weather_temp_gradient": { "fg": "blue_red", "bg": "gray0" },
		"weather_condition_hot": { "fg": "khaki1", "bg": "gray0" },
		"weather_condition_snowy": { "fg": "skyblue1", "bg": "gray0" },
		"weather_condition_rainy": { "fg": "skyblue1", "bg": "gray0" },
		"uptime": { "fg": "gray8", "bg": "gray0" },
		"external_ip": { "fg": "gray8", "bg": "gray0" },
		"network_load": { "fg": "gray8", "bg": "gray0" },
		"system_load": { "fg": "gray8", "bg": "gray0" },
		"system_load_good": { "fg": "lightyellowgreen", "bg": "gray0" },
		"system_load_bad": { "fg": "gold3", "bg": "gray0" },
		"system_load_ugly": { "fg": "orangered", "bg": "gray0" },
		"environment": { "fg": "gray8", "bg": "gray0" }
	}
}
```
I'm not using Powerline since ages, but it seems to me that the good way to go is to copy the default colorscheme for the wm from the ``config_files/colorschemes`` folder, but there's no wm colorscheme there. Any hint?

**Comment by ZyX-I** [comment]
Wondering where is my message from the mail?

**Comment by ZyX-I** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On February 26, 2015 1:13:00 PM EAT, Francesco de Virgilio <notifications@github.com> wrote:
>* OS: Archlinux
>* Powerline:
>[python-powerline-git](https://aur.archlinux.org/packages/python-powerline-git)
>* version: 2.1 (ca6797055a728bb043d0ac46a849949d8efd72ff)
>
>I'm using the mail segment with LemonBoy's
>[Bar](https://github.com/LemonBoy/bar) (compiled on the ``cairo-love``
>branch):
>``/home/fradeve/.config/powerline/config.json``
>
>```json
>    }
>    "ext": {
>        "wm": {
>            "colorscheme": "default",
>             "theme": "fradeve"
>        }
>    }
>```
>
>``/home/fradeve/.config/powerline/themes/wm/fradeve.jsoon``
>```json
>        "email_imap_alert": {
>                "before": "✉ ",
>                "args": {
>                    "server" : "mail.some.org",
>                    "username": "francesco.devirgilio@inventati.org",
>                    "password": ""
>                }
>           }
>```
>``/home/fradeve/.i3/config``
>```bash
>exec python
>/usr/lib/python3.4/site-packages/powerline/bindings/bar/powerline-bar.py
>--i3 | bar -b -f "-misc-dejavu sans
>mono-medium-r-normal--11-*-*-*-m-*-iso10646-1"
>```
>It works perfectly inside Tmux bar, but it errors in wm, due to the
>lack of a colorscheme (the error flicks for just 1 sec on the bar, so
>I'm not able to copy/paste it here, but it has to do with the lack of
>"groups" in ``email_alert`` or something similar).
>The segment works if I create
>``/home/fradeve/.config/powerline/colorschemes/wm/default.json`` with
>this content:
>```json
>{
>	"name": "Default color scheme for window managers",
>	"groups": {
>		"background:divider": { "fg": "gray5", "bg": "gray0" },
>		"session": { "fg": "black", "bg": "gray10", "attr": ["bold"] },
>		"date": { "fg": "gray8", "bg": "gray2" },
>		"time": { "fg": "gray10", "bg": "gray2", "attr": ["bold"] },
>		"time:divider": { "fg": "gray5", "bg": "gray2" },
>		"email_alert": { "fg": "white", "bg": "brightred", "attr": ["bold"]
>},
>		"email_alert_gradient": { "fg": "white", "bg": "yellow_orange_red",
>"attr": ["bold"] },
>		"hostname": { "fg": "black", "bg": "gray10", "attr": ["bold"] },
>		"weather": { "fg": "gray8", "bg": "gray0" },
>		"weather_temp_gradient": { "fg": "blue_red", "bg": "gray0" },
>		"weather_condition_hot": { "fg": "khaki1", "bg": "gray0" },
>		"weather_condition_snowy": { "fg": "skyblue1", "bg": "gray0" },
>		"weather_condition_rainy": { "fg": "skyblue1", "bg": "gray0" },
>		"uptime": { "fg": "gray8", "bg": "gray0" },
>		"external_ip": { "fg": "gray8", "bg": "gray0" },
>		"network_load": { "fg": "gray8", "bg": "gray0" },
>		"system_load": { "fg": "gray8", "bg": "gray0" },
>		"system_load_good": { "fg": "lightyellowgreen", "bg": "gray0" },
>		"system_load_bad": { "fg": "gold3", "bg": "gray0" },
>		"system_load_ugly": { "fg": "orangered", "bg": "gray0" },
>		"environment": { "fg": "gray8", "bg": "gray0" }
>	}
>}
>```
>I'm not using Powerline since ages, but it seems to me that the good
>way to go is to copy the default colorscheme for the wm from the
>``config_files/colorschemes`` folder, but there's no wm colorscheme
>there. Any hint?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/powerline/powerline/issues/1320

I do not see what is the issue? Ever since 1.0 colorschemes consist of three parts (and this is described in the documentation): colorschemes/(name).json, colorschemes/(ext)/__main__.json and colorschemes/(ext)/(name).json, of which any file may be missing (but either the first or the last must be present). These files are merged with each other to form the resulting colorscheme.

So missing wm/default.json file is not the issue. The fact that without color definitions segment is not going to work is not either. Since you have not setup logging then disappearing error is neither (maybe it is an issue that this error is displayed *at all* **in the bar**). If you want to add missing group to the top-level colorscheme then you can file a PR, but first check that it is missing *in develop* (I do not remember when exactly regarding releases, but a number of highlight group locations were moved to top level).
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJNBAEBCgA3BQJU72s1MBwfMDI7PjIgHTg6PjswOSAQOzU6QTA9NEA+MjhHIDxr
cC1wYXZAeWFuZGV4LnJ1PgAKCRBu+P2/AXZZImtYD/9BHkEe7bjJ+oz5Ont4FxKl
X9tt82llpPgnowSL18m7l9GG1SB1AghtOv4uwGojvmD/FM+WLWKjt/m1vEyxQAPD
hkK2hY1Qi+qsm1hcyACKOIaRZ9c0by+HoSiHotYDUy8boFhsA7gLn2ljcBTdp6zc
BChRTcr8qQBMPqVJqnbHGCm9voyemjxWTzZ1V0MESXKRuapFiCotsyU8U3DNnruS
QMN4DTG/++dCo3FOynlU20P8rpvIpFIIZAqfQIeXG8sYqncSoLPcoyio3PAlZgDe
gSJebvyax1+gZliFdBKEDeIQrGhspAnAdpOjSIyvXCWzFSjwsKLlmkGjgAK/uyWm
BBaTAN1qr9Rj4N+khAFwzeN3WbfoHxvJOa9GDA/3UHrc7C+0eqHFiBfXqDVqVtxr
uTUPXYHh4OwP/yMPMQyL4cBL68cqqFVxP5WftQ7m5RiC/0HuZNEoY1tHOZVpMQqS
dHgvYZsSDn5fkD4EBSKU5Wi6vzv12Cm9CDHFdgUI0IRrlDgrBmX3MwhgyMtg4a5D
PE786s8T/sIuAos0KT2I3BfShGJTfh9ZYfYE6opFb/EIbUxvT7bf5QzhP5/LtkkR
zN0EALpCr7jvKGKrjsgcXaxwQbdE1Vg38lvCXyqmMGKOdiANPq7qLWLL5Dyy+wZY
VabmiIhXsKCCQy24e6xERA==
=jXTT
-----END PGP SIGNATURE-----

**Comment by ZyX-I** [comment]
And resending made it appear as “quote only”. Super.

---

I do not see what is the issue? Ever since 1.0 colorschemes consist of three parts (and this is described in the documentation): colorschemes/(name).json, colorschemes/(ext)/__main__.json and colorschemes/(ext)/(name).json, of which any file may be missing (but either the first or the last must be present). These files are merged with each other to form the resulting colorscheme.

So missing wm/default.json file is not the issue. The fact that without color definitions segment is not going to work is not either. Since you have not setup logging then disappearing error is neither (maybe it is an issue that this error is displayed *at all* **in the bar**). If you want to add missing group to the top-level colorscheme then you can file a PR, but first check that it is missing *in develop* (I do not remember when exactly regarding releases, but a number of highlight group locations were moved to top level).
