### ISSUE TITLE
Every time I upgrade or touch anything on powerline everything breaks

### ISSUE THREAD

**Issue by devth** [powerline/powerline#1335]

**Comment by devth** [comment]
Every time I upgrade powerline I have to re-copy the new config files from /usr/local/lib/python2.7/site-packages/powerline to ~/.config/powerline, overwriting any custom config in the process. Why is config never backward compat?

**Comment by ZyX-I** [comment]
Configuration is always compatible unless you upgraded to the next major release (so far there were two, next major release is planned to break things for powerline plugin writers, but not configuration).

And do not recopy configuration files. Ever since the first release this is not required. Currently all configuration files are merged with each other.

**Comment by devth** [comment]
I guess I'll just stop upgrading. Thanks.

**Comment by ZyX-I** [comment]
And have even worse issues should you be forced to upgrade or use configuration files on the other machine? You should read about configuration merging and leave only your custom changes in your configuration files. The way you do now most likely makes it much harder to identify what were the changes.
