### ISSUE TITLE
Glyphs not showing - depending on user?

### ISSUE THREAD

**Issue by dandrzejewski** [powerline/powerline#1345]
After installing the OSX 10.10.3 update, the glyphs do not show when I'm logged in as a normal user, but when I sudo to root, they work fine:

![screen shot 2015-04-10 at 11 36 45 am](https://cloud.githubusercontent.com/assets/181952/7091205/35707eae-df76-11e4-9efb-aaf2f94e19da.png)

I'm sure it's my configuration, but I can't figure out what's broken/different?

**Comment by ZyX-I** [comment]
What is `locale` output in both cases? I guess you for some reason have non-unicode locale while you are the user. You can force using powerline-specific glyphs even in this case, but it is better to fix the issue.

**Comment by ZyX-I** [comment]
Note: if you are using daemon only locale that has *daemon* is significant. If you happened to launch daemon under C locale under your user and under UTF-8 one under root (which is possible because you get user and root shells a different way) then it will not work as well.

To test whether it is the case if `locale` output is the same both as user and root, run `powerline-daemon --replace` as user. This cannot possibly be the case if you are not using daemon. It is also worthless to test if `locale` shows that you have non-unicode locale under user.

**Comment by dandrzejewski** [comment]
Holy smokes, that did it (powerline-daemon --replace).

BTW,  here's my 'locale' command output - it's the same both ways:

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
    LC_CTYPE="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_ALL=

**Comment by ZyX-I** [comment]
@dandrzejewski This means you first run `powerline-daemon` in non-unicode locale. I don’t know when and how this happened, but if this happens again you need to investigate the issue.
