### ISSUE TITLE
Powerline broken with Tmux 2.0

### ISSUE THREAD

**Issue by ssbanerje** [powerline/powerline#1354]
The powerline status line seems to break after TMUX 2.0 update. Any ideas how to fix this?

![1___zsh_tmux_plugin_run__tmux__and_new_issue_ _powerline_powerline](https://cloud.githubusercontent.com/assets/732178/7520379/dfe99ec0-f4ab-11e4-9e14-36625dfbba31.png)

My `.tmux.conf` is --
```
set -g status-right '#(/Users/subho/.powerline/scripts/powerline tmux right)'
source '/Users/subho/.powerline/powerline/bindings/tmux/powerline.conf'
```

And my `powerline.conf` is --
```
if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'
# vim: ft=tmux
```

**Comment by burningTyger** [comment]
Was going to post the same. However, this seems to be an issue with tmux, not powerline. You can for example `:source ~/.tmux.conf` again or just `:source /Users/subho/.powerline/powerline/bindings/tmux/powerline.conf` inside tmux. This will activate powerline again. For some reason it doesn't work with the initial reading of the `.tmux.conf`.

**Comment by phongvcao** [comment]
@burningTyger @ssbanerje you can temporarily solve this problem by adding the following lines at the end of your .bashrc (or .zshrc):

```bash
# The path can be whatever path you installed powerline in...
tmux source "/usr/local/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf"
```

**Comment by phongvcao** [comment]
@burningTyger @ssbanerje actually I figure out that for some reason tmux no longer execute the ```source``` command inside its ~/.tmux.conf at startup anymore. So to fix this problem, you can simply remove (comment out) the ```source``` command from the ~/.tmux.conf altogether:

```tmux
# source "/usr/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf"
```

and add the following lines to anywhere in your ```.zshrc``` (or ```.bashrc```):

```zsh
if [[ -f /usr/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf ]]; then
    tmux source "/usr/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf"
fi
```

**Comment by vados** [comment]
instead source select  source-file "/usr/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf" 
man tmux source-file path
                   (alias: source)
             Execute commands from path.

**Comment by ZyX-I** [comment]
@phongvcao I do not see tmux not executing source command. But it for some reason stopped executing `set-environment -r` (actually this command never did anything useful like it is described in the documentation) and `refresh-client` during configuration loading (they are executed via shell, not present in configuration file). Since almost all environment variables are added by using `set-environment -g VAR val` then `set-environment -r VAR` this stops at first environment variable effectively neitralizing `powerline-config tmux setup`.

Maybe in place of sourcing tmux configuration files I should now execute them from shell line-by-line (or using `cmd1 \; cmd2`), expanding environment variables on my own (should actually make startup faster by lessening number of tmux calls).

**Comment by NHDaly** [comment]
For others who find this: It took me a while to realize what to do to fix this, but it's already fixed here, so I just had to update powerline and everything worked again!

For me that was `pip install --upgrade --user powerline-status`

**Comment by roddykou** [comment]
Try using `source-file` instead of `source` in your .tmux.conf
