### ISSUE TITLE
Powerline wont work on my .zshrc and .bashrc

### ISSUE THREAD

**Issue by musamanyama** [powerline/powerline#1361]
Hi, i have Ubuntu linux 14.04, i have installed and 'sourced' powerline.zsh in my .zshrc (also my .bashrc) but when i start the terminals i get an error saying: 
>
Traceback (most recent call last):                                                                 
  File "/usr/bin/powerline-render", line 15, in <module>
    from powerline.shell import ShellPowerline, get_argparser, finish_args, write_output
ImportError: cannot import name get_argparser
Traceback (most recent call last):
  File "/usr/bin/powerline-render", line 15, in <module>
    from powerline.shell import ShellPowerline, get_argparser, finish_args, write_output
> ImportError: cannot import name get_argparser.

have installed many versions (python, python2, python 2.7, python3 and python 3.4) am not a python programmer but i understand a bit of python codes. Please help cause i couldn't find the solution for my own and i would really love to have powerline working on my shells.. 
Thanks..

**Comment by ZyX-I** [comment]
How exactly did you install it? Line 15 that is shown here is from an outdated version of powerline: `get_argparser` and other functions after `ShellPowerline` class were long since moved to another location.

You must make sure you have only one powerline installation. This situation looks like if you have outdated powerline installation installed into /usr and more up-to-date installed somewhere else (use `python -c 'import powerline.shell; print(powerline.shell.__file__)'` to determine where).

**Comment by musamanyama** [comment]
Hi.. Mr..!! :+1: 
Thank You very much for your response... of course i did multiple installations, first in github which i failed due to my crack-head i would say, but with apt-cache i found python-poweline which i installed and didn't bring anything, i then found the powerline.deb which I installed and i guess it was the one making weird things..
With your response, as i wanted to explain here what powerline github repo was saying.. i managed to uncrack my head.. and they weren't errors..
a quick sudo apt-get remove powerline and 
sudo python ./setup.py build && sudo python ./setup.py install
refreshed my zshrc and bashrc sources and it worked magic...
Thank You very much sir.
