### ISSUE TITLE
Fatal Python error: Py_Initialize

### ISSUE THREAD

**Issue by zchee** [powerline/powerline#1363]
I installed powerline-status on python 3.4 stable.

and, set .vimrc,

```vim
set rtp+="/usr/local/lib/python3.4/site-packages/powerline/bindings/vim"
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
```

but, Display this error when launching vim.

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
Vim: Caught deadly signal ABRT
Vim: Finished.
[1]    53069 abort      vi
```

- python 3.4 stable
- powerline-status 2.1.4 latest
- MacVim homebrew Built from source with --with-python3, --with-lua, --with-luajit, --override-system-vim

What should I do?
Thanks.

**Comment by ZyX-I** [comment]
It is problem with Vim setup, not powerline. I do not know whose exactly problem is this, but you will see exactly the same error when you run any `python3 …` command. Since this is Mac OS (where it is common for users to have brew and non-brew Python) I would first think whether you are trying to use correct Python. (But first action would be testing Python with something like `python3.4 -c 'import encodings'` and reinstalling if it fails.) It is better to ask on vim-use mailing list as I do not usually have problems with Python and I definitely do not have Mac OS.

When asking on vim-use provide a minimal example: just `python3 print(42)` should be enough to trigger the same error.

**Comment by gawbul** [comment]
I did a `brew reinstall vim --with-python3` and this seemed to resolve the issues for me.

**Comment by fingin** [comment]
check your paths variable it might be missing a few things but i don't know

check google
