### ISSUE TITLE
Powerline doesn't work on RedHat 5.10 for vim

### ISSUE THREAD

**Issue by LKI** [powerline/powerline#1365]
Hi, I'm using powerline for vim.

I add this line to .vimrc:
```
set runtimepath+=~/.vim/bundle/powerline/powerline/bindings/vim
```

But I got:
```
Traceback (most recent call last):
  File "<string>", line 9, in ?
  File "/home/l9s/.myconf/unix/dotvim/bundle/powerline/powerline/__init__.py", line 74
     prefix = self.ext + ((':' + prefix) if prefix else '')
                                          ^
 SyntaxError: invalid syntax
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing /home/l9s/.myconf/unix/dotvim/bundle/powerline/powerline/bindings/vim/plugin/powerline.vim:
line  157:
  File "<string>", line 50
    ee = lambda *args, **kwargs: echoerr(*args, stream=sys.stdout, **kwargs)
                                                     ^
SyntaxError: invalid syntax
```

It seems that my python version is too low...(Which is actually too low as Python 2.4.3)
But I can't upgrade python since *yum* depends on python...

How to fix this problem?

**Comment by ZyX-I** [comment]
You should update your Python version. 2.4.3 is not supported and will never be because I can write code that works on Python 2.6, 2.7, 3.2…3.4, but not code that works on Python 2.5 and 3.x, not to mention 2.4 because only in Python-2.6 `__future__` imports and some other features were added to make 3.x+2.x-conformant code possible to write.

You can compile your own Vim and your own Python and install both to `$HOME/.local` (or any other directory, just make sure that dynamic linker knows where Python libraries are, on my system (Gentoo) this is controlled by `LDPATH` setting defined in `/etc/env.d/*`). This is possible without breaking yum, but there are good chances that yum will not break by updating Python because 2.x versions were keeping backwards compatibility.

**Comment by LKI** [comment]
Thanks~
