### ISSUE TITLE
Tmux doesn't automatically truncate

### ISSUE THREAD

**Issue by gregf** [powerline/powerline#137]
Not sure how possible this is with tmux themes, but tmux doesn't currently automatically truncate like vim does.

I'm use a tiling window manager, and with two tmux sessions side by side the status bar is nearly useless. With 3 of them the status bar stops producing any information at all.

![2013-01-26-115343_1679x98_scrot](https://f.cloud.github.com/assets/980/99966/05735558-67d9-11e2-9670-7128569765d8.png)

![2013-01-26-115407_1679x99_scrot](https://f.cloud.github.com/assets/980/99968/14a9ecbc-67d9-11e2-923f-f3cc7e927b15.png)

**Comment by philbert** [comment]
Is there a way to change the behaviour of the segment truncation in tmux? 

I run several windows in tmux and would like to prioritise the display of those over pretty much anything on the right hand side, because all of that information I can see from elsewhere on my screen. 

<img width="1077" alt="screen shot 2016-01-24 at 20 55 12" src="https://cloud.githubusercontent.com/assets/5618563/12538560/da1c6df6-c2dc-11e5-9564-428f1cd0aa5d.png">

<img width="919" alt="screen shot 2016-01-24 at 20 54 02" src="https://cloud.githubusercontent.com/assets/5618563/12538552/b47e45a6-c2dc-11e5-9232-551cad569e1b.png">

<img width="663" alt="screen shot 2016-01-24 at 20 56 22" src="https://cloud.githubusercontent.com/assets/5618563/12538565/fa45d0f4-c2dc-11e5-929d-1bbf62350b7c.png">
