### ISSUE TITLE
Symbols not displaying when using launchd to start powerline-daemon

### ISSUE THREAD

**Issue by gsong** [powerline/powerline#1380]
If I start `powerline-daemon`, either in daemon or foreground mode, using a bash shell, then the bash prompt displays symbols properly.

However, if I use launchd on OS X to start `powerline-daemon`, everything functions properly, but the bash prompt won't display the symbols.

Any idea how I should troubleshoot?

**Comment by ZyX-I** [comment]
Powerline uses locale to determine the output encoding. When you use daemon output encoding is determined only once at startup and using environment daemon was launched in (mainly because I do not know how to make functions from `locale` module use given environment without modifying `os.environ` (which is not an option because this is global)).

If launchd does not specify correct locale and powerline detects used encoding as e.g. ASCII (this is normal for C locale which is the default) then it will only ever return ASCII characters. In this case powerline theme is automatically set to `ascii` unless it is provided in configuration, but forcing `powerline` theme makes no sense because output will be in encoding specified by locale.

**Comment by gsong** [comment]
@ZyX-I Through tracing the code I figured that out (`get_preferred_output_encoding()`). Simply setting `LANG=en_US.UTF-8 ` in launchd worked like a charm. Thank you for the quick reply.

**Comment by rspeed** [comment]
Long since closed, but here's the launch agent I made:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Disabled</key>
	<true/>
	<key>EnvironmentVariables</key>
	<dict>
		<key>LANG</key>
		<string>en_US.UTF-8</string>
	</dict>
	<key>KeepAlive</key>
	<dict>
		<key>Crashed</key>
		<false/>
		<key>SuccessfulExit</key>
		<true/>
	</dict>
	<key>Label</key>
	<string>homebrew.mxcl.powerline-daemon</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/sh</string>
		<string>-lc</string>
		<string>/usr/local/bin/powerline-daemon --foreground</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

It's disabled by default, so you'll need to use the `-w` flag when running `launchd enable`.
