### ISSUE TITLE
tmux displays config on first session startup..

### ISSUE THREAD

**Issue by wrfc** [powerline/powerline#1394]
When starting a fresh tmux session, a message displaying what seems to be the running config is displayed. The message does not get displayed on subsequent sessions I open, nor when I disable powerline on my .tmux.conf file. It is my first day using the plugin on tmux, so I'm not sure if this is a normal occurrence.

![tmux startup](http://imgbin.org/images/24259.PNG)  

I currently have the following lines on **.tmux.conf**
`run-shell "powerline-daemon -q"`
`source "/usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/powerline.conf"`
`set-window-option -g utf8 on`
`set -g default-terminal "screen-256color"`

Thanks you.

**Comment by ZyX-I** [comment]
You need to update your tmux version (AFAIR first version without this behaviour is either 1.8 or 1.9). On old tmux versions this is mostly “won’t fix” (fixing issue will make code rather complex) or “can’t fix” (“don’t know how to fix”) (fix is either not possible or, more likely, I did not invest too much time in it). Since this happens only when tmux server starts such behaviour is not too intrusive.

**Comment by wrfc** [comment]
Updated, and problem solved. Thanks again!

**Comment by binarykitchen** [comment]
I have the same problem and do not want to see the config display. Using the latest version here:

```
$ pip show powerline-status                                                                                                                                                                              1 
---
Metadata-Version: 1.1
Name: powerline-status
Version: 2.1.4.dev9999-git.0dc5c391fbc045ecbf3836368dea4ee4e2cb7ace
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

So, updating apparently won't help for me. Any clues how I can disable this with a configuration entry?

**Comment by ZyX-I** [comment]
@binarykitchen 

1. 2.1.4 is not the latest version.
2. Powerline version is irrelevant. You need to update tmux.

**Comment by binarykitchen** [comment]
Oh ... ok, I already have

```
$ tmux -V
tmux 1.8
```

**Comment by ZyX-I** [comment]
@binarykitchen Latest tmux is 2.0. I am pretty sure that 1.9\* are not affected, but do not remember about 1.8: apparently it is.

**Comment by ZyX-I** [comment]
I personally have 1.9a.

**Comment by binarykitchen** [comment]
Hmmm, I installed it via `apt-get` and v1.8 is the latest.

**Comment by binarykitchen** [comment]
https://gist.github.com/P7h/91e14096374075f5316e helped ... all good now

**Comment by joshkel** [comment]
As others have noted, Powerline still works in tmux 1.8, you just have to press Enter or Ctrl-C to clear the config. Since Ubuntu 14.04 LTS is affected by this bug, and since there are some advantages to staying with LTS packages, an evil dirty hack to fix the problem is to add `send-keys Enter` to your `~/.tmux.conf`, after sourcing powerline.conf.
