### ISSUE TITLE
time.cpython-34m.so: undefined symbol: PyExc_OSError

### ISSUE THREAD

**Issue by wlyfls** [powerline/powerline#1396]
![vimpowerlineerror](https://cloud.githubusercontent.com/assets/1650090/8183601/c7a872ca-146b-11e5-9ec5-458e931242e0.png)
When I start vim,it shows the window.

**Comment by ZyX-I** [comment]
This is an error in your Python installation or in Vim (like #1385), not in powerline. You will get the same error if you do `vim -u NONE -i NONE -c ':python import logging'`. If you get the same error when you do `python -c 'import logging'` then you should report it to your distribution Python package maintainer. Otherwise to Vim package maintainer.
