### ISSUE TITLE
workaround for strange characters in vim

### ISSUE THREAD

**Issue by norbertklar** [powerline/powerline#1397]
Just wanted to write a quick guide for vim users, who using/or want to use powerline, but they get strange characters. I know Lokaltog/powerline is deprecated, but still, many uses that.

1. Install Lokaltog's powerline: https://github.com/Lokaltog/vim-powerline
2. Install patched-fonts(https://github.com/powerline/fonts), and set the new fonts in your terminal, like: Ubuntu Mono derivative Powerline
2. Copy this to your .vimrc file:
```
set laststatus=2
let g:Powerline_symbols = 'fancy'
set termencoding=utf-8
set encoding=utf-8
let g:Powerline_dividers_override = ["\Ue0b0", "\Ue0b1", "\Ue0b2", "\Ue0b3"]
let g:Powerline_symbols_override = { 'BRANCH': "\Ue0a0", 'LINE': "\Ue0a1", 'RO': "\Ue0a2" }
```

And thank god, it's working!

![ehqesln](https://cloud.githubusercontent.com/assets/9632419/8311900/ba131dae-19d9-11e5-8886-6d1c393125f7.png)

**Comment by ZyX-I** [comment]
Lokaltog/powerline is not deprecated, it is Lokaltog/vim-powerline. And this is not the right place to put this information: finding relevant question on SO (now VSE? (https://vi.stackexchange.com)) and answering it is better.

Also setting termencoding to UTF-8 is not needed:

1. If locale is UTF-8 then nothing needs to be done at all.
2. If locale is not UTF-8, but terminal thinks it is (common if terminal emulator itself was launched with `LANG=….UTF-8`, but Vim or shell was launched with `LANG=C` for some reasons) setting &encoding is *enough* because &termencoding defaults to empty (== “use the value from &encoding”).
3. In other cases you will see broken output.

So having `set encoding=utf-8` is enough.
