### ISSUE TITLE
Unused Right-hand Column

### ISSUE THREAD

**Issue by t3chguy** [powerline/powerline#1403]
![powerline](https://cloud.githubusercontent.com/assets/2403652/8520753/3ce062e6-23d5-11e5-9559-b0b9cc752e5b.JPG)
As you can see, I am using Powerline (Daemonized) for both Tmux and Fish, but the powerline within Fish isn't flush to the right hand side like the tmux one is, this isn't the case only within tmux, I can actually place my cursor outside of the red user segment. Any ideas what could be causing this behaviour?

**Comment by ZyX-I** [comment]
You should treat this as either fish bug or your configuration error. Two facts:

1. Powerline supports outputting line above the prompt.
2. If powerline does this and it occupies the *whole* line including the last column this line will not be displayed.

Fish bindings do not know whether there is above line. You can though tell them to ignore above line even if it is defined in configuration: set `POWERLINE_NO_FISH_ABOVE` or `POWERLINE_NO_SHELL_ABOVE` configuration variable to 1: this way bindings will not add space that is needed only to make above lines align with below ones.

If you happen to switch to zsh fixing will be different because space is added by zsh; also fix may actually cause visual bugs (zsh terminal handling is rather different and they have space for a reason). In tcsh it is impossible to fix (though I do not know anybody willing to switch to it, especially from modern shells like zsh/bash/fish).

**Comment by t3chguy** [comment]
Adding `set POWERLINE_NO_FISH_ABOVE 1` to my config.fish fixed it, are there any cons of having this set?

**Comment by ZyX-I** [comment]
@t3chguy As I said you will never see lines above the prompt. But this is only if you define them in your theme, by default there is nothing like this.
