### ISSUE TITLE
Powerline-config tmux exiting with status 127

### ISSUE THREAD

**Issue by damienstanton** [powerline/powerline#1424]
Running OS X 10.11 Beta 6, and Bash 3.2.

It seems that the rootless changes to the way the system Python are able to access `/usr` is causing an issue with powerline-config. 

Tmux is unable to show any components in the powerline statusbar and when trying to manually source .tmux.conf from within tmux the following is returned:

```
'powerline-config tmux setup' returned 127
```

**Comment by ZyX-I** [comment]
Exit status 127 means “command not found”. It has absolutely nothing to do with /usr *unless* pip (or brew?) installed powerline to /usr. For powerline-config to work it must be contained in some directory in $PATH, *and* $PATH must be defined this way *before* tmux server is started.

**Comment by damienstanton** [comment]
You are correct; It appears that the brew-installed /Library/Python/2.7/bin dir was not added to `PATH` automatically. Doing so has resolved the issue.

I've run into many brew issues so far in the 10.11 beta, so this is not surprising. Thanks for the quick reply.

**Comment by vchernomor** [comment]
fixed for me:

$ brew install powerline
==> Downloading https://homebrew.bintray.com/bottles/powerline-2.3.el_capitan.bottle.tar
######################################################################## 100.0%
==> Pouring powerline-2.3.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/powerline/2.3: 198 files, 631.4K
vit@pro 11:59:21 [ ~ ]
$ powerline
powerline         powerline-daemon  powerline-render  
powerline-config  powerline-lint  


then Prefix + ALT+U works fine. 

Problem appeared after migrating from Linux to OSX ;)

**Comment by binarykitchen** [comment]
I am still having this problem, all the above suggestions didn't help @ZyX-I 

Setting up the python paths here in .zshrc only (not in any bash files) and using pyenv:

```
michael-heuberger@abc ~ ❯❯❯ which powerline-config
/home/michael-heuberger/.pyenv/shims/powerline-config
```

loading pyend like that in .zshrc

```
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
```

**Comment by kmgolden** [comment]
The .../tmux/powerline.conf file reads:

`
if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'
# vim: ft=tmux
`
So, this issue is resolved if I add `env "$POWERLINE_CONFIG_COMMAND" tmux setup to ~/.bash_profile

But I then get an error in bash that says approximately 'env not defined'

I think it would be better to just drop the if-shell requirement in powerline.conf to

`
run-shell "powerline-config tmux setup"
# vim: ft=tmux
`

Since we're already only calling this config file from .tmux.conf to begin with.
