### ISSUE TITLE
Not worked with Linux Mint 17.2.

### ISSUE THREAD

**Issue by zw963** [powerline/powerline#1458]
I use Slackware 14.1 before, It worked for me like this:

![snap1](http://zw963.bitbucket.org/powerline2.png)

But, when I switch to Linux Mint 17.2, it not work, like this;

![snap1](http://zw963.bitbucket.org/powerline1.png)

Is there any details I need to to for this? 

Thanks.

**Comment by zw963** [comment]
After do some hack,  currently , it show as this:

![snap3](http://zw963.bitbucket.org/powerline3.png)

Anything wrong ?  Thanks.

**Comment by ZyX-I** [comment]
`⚡ NN:MM` (which looks like “remaining time until battery is empty”), separators between first two segments being different from separators after last two, prompt ending with `$` and sign between it, and absent `Downloads` (last directory component) highlighting suggests that you have either written *very* huge part of the configuration from scratch, with some non-trivial configuration hacks, or you are not using this project at all.

Since this is very unlikely please provide your configuration. Until then I assume you are using another project and closing this issue.

**Comment by zw963** [comment]
Hi, here is my config with bash. Thanks.

https://github.com/zw963/ass/blob/master/common/functions/linux/ps1.sh#L225-L232

**Comment by ZyX-I** [comment]
This has nothing to do with this project. Neither it is using powerline glyph: most likely you have somewhere found glyph used by vim-powerline and have taken it as SEGMENT_SEPARATOR. Vim-powerline used to require replacing some uncommon existing glyph with its glyph in place of using unicode private use area designed specifically for such needs.

**Comment by zw963** [comment]
Thank for you reply. I will try to fix this with your tips.
