### ISSUE TITLE
Enable powerline.service by default?

### ISSUE THREAD

**Issue by jcharaoui** [powerline/powerline#1477]
As maintainer of the powerline package in Debian, I have the option to either install and enable the powerline systemd service file by default when users install the package, or simply provide it as an example in the documentation. Which do you prefer, developpers?

**Comment by ZyX-I** [comment]
If this was Gentoo I would say that it makes sense with USE=zsh, tmux, bash, fish, dash, mksh, busybox or rc and USE=systemd: when user is not using powerline shell or tmux bindings service provided by this daemon is useless. It is harmless to launch this service, though, but without USE flags it will run unneeded process for those users which use powerline only in Vim (or in some system (WM) statusline, but this is rather unlikely).

I cannot have any preference here because I am missing critical pieces of information like

- How it is easy to enable (if it is “example in the documentation”)/disable (if it is installed and enabled in documentation) the service?
- What users exactly will use it?
- How long does it run (e.g. if it is only used by user which rarely connects to server via ssh)?
- What is common practice in debian? In Gentoo AFAIK *no* services are enabled by default.
- How many users are *not* using tmux and shell bindings compared to all powerline users?
