### ISSUE TITLE
tmux status-right w/ powerline shows code briefly before rendering

### ISSUE THREAD

**Issue by dbingham** [powerline/powerline#1502]
I recently made a big version jump up to tmux 2.1 and powerline 2.3 from some ancient version (sorry, don't remember what versions).  Took me a while to get the configs sorted out, but everything seems to be working now except for a strange rendering issue in tmux.  When I first switch windows in a tmux session, the status-right will flash showing code, then usually in less than a second it resolves to render the segments.

Here is what it looks like when it flashes the code:
<img width="949" alt="screen shot 2015-11-24 at 9 02 51 am" src="https://cloud.githubusercontent.com/assets/131392/11374737/6db65a12-928c-11e5-995b-eecd5197a1f6.png">

And then when it resolves <1sec later:
<img width="381" alt="screen shot 2015-11-24 at 9 14 57 am" src="https://cloud.githubusercontent.com/assets/131392/11374743/7aef9ea0-928c-11e5-80e9-1b706eb31c0d.png">

I honestly don't know if this is a bug in tmux, powerline, or my config, but it is quite distracting when I'm working on something and I'd really appreciate any help figuring out the cause.

**Comment by ZyX-I** [comment]
I cannot do anything with this. Report the issue to tmux authors if you want it fixed (in a form “if I set `status-right` option to something long running (e.g. `sleep 1`) tmux …”: this issue has nothing to do with powerline and tmux developers will not be happy to install it). Note that the only sane alternative is making the status line blank: when tmux displays what it displays it does it because it has nothing else to display as command did not yet finish running.

**Comment by dbingham** [comment]
Ok.  Perfect.  Thanks for pointing me in the right direction.

**Comment by ZyX-I** [comment]
I do not remember exactly what tmux was doing before 2.1, but I think it was displaying nothing.
