### ISSUE TITLE
 offline battery symbol

### ISSUE THREAD

**Issue by fdelacruz** [powerline/powerline#1506]
I've searched all over the internet similar to the ones used by the online battery, uptime, time segment and haven't able to find any. There's just a big gap when I switch to using the battery and I would love the have a battery symbol there. Can anybody help?

**Comment by ZyX-I** [comment]
Do not search the internet, do read documentation. Offline battery symbol is controlled by a [offline](https://powerline.readthedocs.org/en/latest/configuration/segments/common.html#module-powerline.segments.common.bat) argument, expected to be set using [args](https://powerline.readthedocs.org/en/latest/configuration/reference.html#config-themes-seg-args) segment through [segment_data](https://powerline.readthedocs.org/en/latest/configuration/reference.html#config-themes-segment-data) dictionary in [~/.config/powerline/themes/__main__.json](https://powerline.readthedocs.org/en/latest/configuration/reference.html#themes), examples are in the [default configuration](https://github.com/powerline/powerline/blob/eaa772f19538b00342661dfa1b88aca6b9ac69ab/powerline/config_files/themes/powerline.json#L50-L57) (you do not have to copy *all* arguments from there).

**Comment by fdelacruz** [comment]
I do know how to set said [offline](https://powerline.readthedocs.org/en/latest/configuration/segments/common.html#module-powerline.segments.common.bat) parameter. I was asking for a symbol to set it with since I haven't able to find one aside of unicode which are apparently not supported by this segment.

**Comment by ZyX-I** [comment]
@fdelacruz Unicode symbols are the *only* ones supported. But this does not mean that your font contains necessary glyphs. Also if you happened to use powerline in non-unicode locale you will not be able to see any unicode character that cannot be represented in the locale encoding (this is one of the common problems with tmux: sometimes tmux server for some reason is started in wrong locale and locale is then fixed by the shel inside tmux).
