### ISSUE TITLE
[Pycharm] Terminal have a wrong arrows

### ISSUE THREAD

**Issue by SalahAdDin** [powerline/powerline#1528]
Hi guys

I like powerline and i think that is beautiful, i haven't any problem with terminal and guake terminal, but, with Pycharm terminal i have:
![seleccion_105](https://cloud.githubusercontent.com/assets/5034215/13022263/22d4cb76-d1ae-11e5-992d-b21b67875ff6.png)
The arrows are showed as `ff..` or are put backed, i don't know why happen this.

Thank you very much.

**Comment by ZyX-I** [comment]
If your terminal does not support fallback font/you have not told terminal to use powerline font/terminal is not going to display characters from private use area correctly/… it is not a powerline issue. There is a mailing list for this, but first check your terminal documentation. You may also switch to `unicode` theme so that powerline will not be using arrows at all.

**Comment by SalahAdDin** [comment]
But, this isn't problem with guake or terminal, it's a Pycharm terminal problem.

**Comment by ZyX-I** [comment]
Terminal displaying characters incorrectly is not a *powerline* issue, so it must not be opened in this issue tracker. Theoretically there is a powerline mailing list for such questions, but it is better to ask other pycharm users or developers.

**Comment by ZyX-I** [comment]
I am not using pycharm, so can’t help with this problem. `ff` there actually looks more like pycharm using code points which powerline uses for its own purposes, but it may as well be such strange replacement character for absent glyphs.
