### ISSUE TITLE
Minute missing in tmux powerline

### ISSUE THREAD

**Issue by apheleia** [powerline/powerline#1576]
# Issue
Given that I installed powerline
When I open a tmux session
Then the powerline should be shown, including the full minutes
But instead, the second of the two minutes is always missing

## Info
See this screenshot, which displays the issue:
![missing_minute](https://cloud.githubusercontent.com/assets/1196244/14667107/c47eea6a-06dd-11e6-9666-d0374cd0bfd5.png)

The issue is not specific to a certain time.

OS: Arch linux
powerline version: `2.4-1`
tmux version: `2.2-1`

**Comment by ZyX-I** [comment]
This is because watch glyph is too bold to be displayed in one cell because it is borrowed from the other font. So glyph shifts the segment because it is bold and minute gets shifted under the next glyph. You need to change font or to change watch glyph (copy only the part of the `powerline/config_files/themes/powerline.conf` which contains this glyph to `~/.config/themes/powerline.conf` with this glyph replaced).

**Comment by apheleia** [comment]
Thank you!
