### ISSUE TITLE
powerline not appearing in zsh

### ISSUE THREAD

**Issue by Disembodied** [powerline/powerline#1593]
Hi guys,

Arch Linux user here. I use rxvt-unicode. Powerline is not working for zsh, I followed the instructions and I've configured ~/.zshrc with the `powerline-daemon -q` and the `source /usr/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh` instruction. Already did a `whereis` to find out where python and powerline are, and I managed to put them into the `$PATH` environment variable so I ended up adding **/usr/lib/python3.5**, **/usr/bin/python3.5**,e **/usr/bin/powerline**. 

First time I installed it via `pacman`, tried uninstalling and going again with` pip`, nothing changed.  Manually running `source /usr/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh` does nothing.

I've already googled and searched for previous issues as well as looked up at the troubleshooting page, but can't really seem to find something that fits my case. Got any ideas? 

Thanks.

EDIT: pressing ` in the terminal makes a"Powerline-like" tab appear. It says "bquote" in it. not really sure what that means though. Still have the issue

**Comment by ZyX-I** [comment]
None of the paths you added should be in `$PATH`. `$PATH` is a list of *directories* where *executables* are located. First item is directory with python3.5 modules and not executables. Second and third are executables and not directories.

Check what happens if you do

    # zsh -f -x
    % source /usr/lib/…/powerline.zsh

    # env -i PATH=$PATH zsh -f -x
    % source /usr/lib/…/powerline.zsh

    # powerline-lint

**Comment by Disembodied** [comment]
Thanks for the reply @ZyX-I.

` zsh -f -x
% source /usr/lib/…/powerline.zsh`

Seems to make it work but each time I type something it spits out:
Link to img: [here](http://i.imgur.com/yhkUPXs.png)

`+_powerline_set_jobnum:11> _POWERLINE_JOBNUM=0                                  
+_powerline_set_main_keymap_name:1> local REPLY
+_powerline_set_main_keymap_name:2> _powerline_get_main_keymap_name
+_powerline_get_main_keymap_name:1> REPLY=+_powerline_get_main_keymap_name:1> bindkey -lL main
+_powerline_get_main_keymap_name:1> REPLY=viins 
+_powerline_set_main_keymap_name:3> _powerline_set_true_keymap_name viins
+_powerline_set_true_keymap_name:1> _POWERLINE_MODE=viins 
+_powerline_set_true_keymap_name:2> bindkey -lL viins
+_powerline_set_true_keymap_name:2> local plm_bk='bindkey -N viins'
+_powerline_set_true_keymap_name:3> [[ 'bindkey -N viins' == bindkey\ -A* ]]
+zsh:5> powerline shell aboveleft -r .zsh '--last-exit-code=127' '--last-pipe-status=127' '--renderer-arg=client_id=4161' '--renderer-arg=shortened_path=~' '--jobnum=0' '--renderer-arg=mode=viins' '--renderer-arg=default_mode=' '--width=79'
+zsh:5> powerline shell right -r .zsh '--last-exit-code=127' '--last-pipe-status=127' '--renderer-arg=client_id=4161' '--renderer-arg=shortened_path=~' '--jobnum=0' '--renderer-arg=mode=viins' '--renderer-arg=default_mode=' '--width=79'`

With the second set of commands you gave me I get this: [Link to img](http://i.imgur.com/LgxdmX8.png)
I also get a long output line, I put it in [pastebin](http://pastebin.com/mXPzXkDT) to avoid bloaing this page.

`# powerline-lint` just executes and outputs nothing.

Got any clues?

**Comment by ZyX-I** [comment]
@Disembodied `zsh -f -x` is needed to

1. `-f`: make your own configuration not affect the result.
2. `-x`: log every command zsh runs in case issues is not with your configuration.

I.e. I suggested that my bindings fail and you post the log of the failure. You are not supposed to actually *use* run shell, so “each time you type something” is OK (though you may disable this with `set +x`).

Second set of commands is for checking whether problem was in environment. Since first one worked this is not the case.

`powerline-lint` checks for problems in configuration (though ignoring overrides from environment). Empty output means everything is fine.

Now I know that you need to find something in your configuration (e.g. ~/.zshrc) which prevents powerline from working: it is neither powerline issue nor some issue during installation. Most likely you have something like a prompt theme which e.g. overrides PS1 each time `precmd` hook is run (I saw such things, though this is more common in bash world then in zsh).
