### ISSUE TITLE
RHEL install fails with version number detection

### ISSUE THREAD

**Issue by gaborbernat** [powerline/powerline#1599]
pip install --user --editable={path}

fails with: 
ValueError: ("Expected ',' or end-of-list in", u'powerline-status==2.4.dev9999+git.d115012b3b442917dcdfb7ea674d3dc3c9da17ce', 'at', u'+git.d115012b3b442917dcdfb7ea674d3dc3c9da17ce')

**Comment by ZyX-I** [comment]
What are `pip`, `setuptools` and `distutils` versions? It looks like you have an outdated one somewhere because the version you are seeing is a proper semantic version and it is handled just fine. Though where requirements are written `+` is being replaced by `-`; this is done by setuptools/distutils I guess.

**Comment by gaborbernat** [comment]
Indeed the pip version was older, once upgraded it worked.
