### ISSUE TITLE
Select symbols not being displayed under urxvt

### ISSUE THREAD

**Issue by css459** [powerline/powerline#1603]
Some. but not all, Powerline symbols are not being shown for Airline in zsh. 

I'm using this for my font under .Xresources
`URxvt.font: xft:Hack-Regular:pixelsize=22,xft:PowerlineSymbols`

These are the symbols not being displayed, according to the airline help page

![sym](https://cloud.githubusercontent.com/assets/16902421/15588333/61bbea78-235b-11e6-9141-636af08a7d2b.png)

This is what airline looks like 

![vimerror](https://cloud.githubusercontent.com/assets/16902421/15588342/6e5b4274-235b-11e6-97d1-3c347e3319f6.png)

And this is what zsh looks like, there shoud be an 'x' where that box is

![zsherror](https://cloud.githubusercontent.com/assets/16902421/15588357/7ffd34a6-235b-11e6-8948-9c8a8f7c721d.png)

`$TERM` outputs to `rxvt-unicode-256color`

**Comment by ZyX-I** [comment]
Airline is not supported here. If you want to ask about specific glyph, shows its *code point* (e.g. `U+ABCD`), do not post useless screenshot from where I have no way to get it. Most likely airline simply uses glyphs which were not defined in PowerlineSymbols because they are not powerline custom glyphs.
