### ISSUE TITLE
Error in `/usr/bin/python': realloc(): invalid pointer

### ISSUE THREAD

**Issue by metalmac** [powerline/powerline#1634]
Hello Guys,

I already installed the powerline-status by pip in my Ubuntu 14.04 ,and configured well.

But when I sshed to my Ubuntu 14.04 via putty, and repeatedly typed in Ctr+C in command line ,it showed "Error in `/usr/bin/python': realloc(): invalid pointer" and poped out the "Fatal Python error: non-string found in code slot" when I tried to open a new tmux seesion (FYI, I didn't create any tmux session before this), and showed "couldn't find my command"(the English meaning of "未能找到命令") just like I typed the wrong command.

And the issue seemed existed int the powerline-render script,as shown in the image below

The powerline install information is shown below

   Name: powerline-status
Version: 2.5
Location: /usr/local/lib/python2.7/dist-packages

PS: I installed my Ubuntu 14.04 in VirtualBox .
![linux_python_error 2016-08-12_160442](https://cloud.githubusercontent.com/assets/1448776/17616301/6c3d5eea-60a6-11e6-8066-912099429c3a.jpg)
![linux_python_error 2016-08-12_160418](https://cloud.githubusercontent.com/assets/1448776/17616302/6c410216-60a6-11e6-8862-a0555278f9d6.jpg)

![Uploading erro.jpg…]()

How can I do with that ? Thank you

**Comment by ZyX-I** [comment]
You should report this to Python bug tracker (but first update python version). I am not a CPython interpreter developer and this is by no means a powerline bug, only CPython interpreter itself calls realloc() directly.

Also for performance reasons I would not suggest to use powerline-render script. If you run powerline-daemon then powerline command should use the daemon in place of the powerline-render script.

**Comment by ZyX-I** [comment]
Basically I would suggest to

1. Try with powerline-daemon. Maybe it will not trigger the bug.
2. Use different Python interpreter: powerline officially works also with CPython-3\* and PyPy (both 2\* and 3\* branches). Jython and IronPython are not tested. Different Python implementations have different set of bugs.

If CPython version is latest then in any case report the bug.

**Comment by metalmac** [comment]
Thank you for your advice:

PS: It's very strange that I didn't use powerline-render by myself manually, it triggered automatically, after I finished all the basic setups.

**Comment by ZyX-I** [comment]
@metalmac `powerline` is a script (or binary compiled from a small C script) which generates used prompt/statusline in many cases, including shell and tmux bindings. If `powerline-daemon` was not launched (or it failed to use daemon’s socket, e.g. because daemon was launched so it will use something non-standard) `powerline` will fall back to `powerline-render` script which does basically the same thing, except that it initializes powerline each time it is called what does not allow to support segments run in background threads or using filesystem watchers (etc, some performance-related things). You are not supposed to call either `powerline` or `powerline-render` directly, shell/tmux/etc bindings call `powerline` by themselves. But `powerline-daemon` is not run by the bindings because it is not always wanted.
