### ISSUE TITLE
tmux seems to update cursor position every second with powerline enabled

### ISSUE THREAD

**Issue by Yuubari** [powerline/powerline#1645]
As described above, it seems like with powerline enabled, tmux either redraws the status line every second, or just moves the cursor around. In PuTTY this renders terminal scrolling (PuTTY's native scrollback) completely broken, as the window position is restored to bottom-of-scrollback every time new data comes in.

There is no periodically updated data other than date/time (without seconds) shown in my status line. Removing the date/time segments does not help. Is there something I can do about this?

**Comment by ZyX-I** [comment]
It is only tmux which controls redraw time, not powerline or something else. Powerline configuration files tell tmux to redraw every two seconds and additionally tmux will redraw status line in any case on some events. I would first try `tmux set-environment -g POWERLINE_COMMAND echo`, this should make it sure that powerline itself is not related (this should make tmux display arguments of powerline command instead of using powerline). Second try tmux default config with something in `status-right` and `status-interval 2`.

And, in any case, PuTTY native scrollback is not a thing you should use with tmux, tmux has its own scrollback. With my configuration tmux even runs in altscreen which automatically disables scrollback in all terminals I know, including tmux itself (I mean, app that uses altscreen while in tmux will disable scrollback in copy mode for the pane it is used in for the time while it is in altscreen, not some more general problem with scrollback).

**Comment by pazniak** [comment]
Similar issue was solved in my case by disabling `terminal > autowrap` .

![image](https://user-images.githubusercontent.com/9994811/148849898-5d43b4d6-d8d5-42d7-baf2-2610cb20eff1.png)
