### ISSUE TITLE
how to change the distance among different parts of tmux status bar.

### ISSUE THREAD

**Issue by springmoonlight** [powerline/powerline#1654]
As shown in the following figure, I would like to change the distance, but I do not find how to configure the attribute in the source code. 
![bf8194cc36d91b0f90964547799c0291](https://cloud.githubusercontent.com/assets/1595077/19217718/1bbad966-8e14-11e6-98aa-5bcd202527f1.png)

**Comment by ZyX-I** [comment]
You cannot find this because this is not supported. The “segments” you see come from a few `window-status-…` options which are set based also on [spaces and dividers](http://powerline.readthedocs.io/en/master/configuration/reference.html#themes) options. Options are set so that “normal” segments look good, but the “segments” you are seeing has only choices between “too much spaces” (current), “too low spaces”, “when iterating over windows segments will shift” and “this will look inconsistent in certain common cases” (first highlighted space is there for this reason: when setting `window-status-…` options powerline cannot know whether preceding “segment” is that `0` or ` 2 > zsh `).

The only option I have ever imagined to deal with all those left “segments” issues is disabling them completely and emulating in powerline, but this means a) asynchronous tmux calls and b) much slower reaction on user input. Neither is desired.
