### ISSUE TITLE
System load gradient

### ISSUE THREAD

**Issue by AcidScorpion** [powerline/powerline#1663]
**Powerline Version: 2.5**
**OS: CentOS 7.2.1511**
**Installed By:** pip install --user git+git://github.com/powerline/powerline

For some reason **threshold_good** and **threshold_bad** doesn't work for me in _powerline.segments.common.sys.system_load_ segment. Gradient colours doesn't changing
In case, if
```json
{
    "function": "powerline.segments.common.sys.system_load",
    "args": {
    "threshold_good": "1.0",
    "threshold_bad": "1.5"
},
```
or
```json
{
    "function": "powerline.segments.common.sys.system_load",
    "name": "system_load_gradient",
    "args": {
        "threshold_good": "1.0",
        "threshold_bad": "1.5"
    },
},
```
Without arguments works.
Also working if change _threshold_good_ or _threshold_bad_ in .../powerline/segments/common/sys.py

**Powerline Version: 2.5.1**
**OS: Fedora release 24**
**Installed By: dnf install powerline tmux-powerline** 

In case if add arguments with threshold in Fedora, load average doesn't show at all.

**Comment by ZyX-I** [comment]
`threshold_good` and `threshold_bad` are floating-point. You can use integers now, but there is no way it is supposed to work when you write strings. In fact, system_load segment did not disappear only because your error was covered by some other. I see at least two other errors in your example configurations:

1. Trailing comma is not allowed in JSON.
2. `"name": "system_load_gradient"` is *not* the way you may use to get gradient. The only thing you may do by placing `"name"` key is disabling default configuration.

**Comment by AcidScorpion** [comment]
OK, good
I don't want to say, that my examples are correct and just looking for the way, how to _make own threshold_ for load gradient, based on documentation. I also tried to use integers, didn't work as well. Ideally, it has to be fractional numbers, like they show in load average output to easily use them in _threshold_good_ or _threshold_bad_.
If you have working solution, please write here. Otherwise, it's look like a bug for me.

**Comment by ZyX-I** [comment]
@AcidScorpion `"1.0"` is a *string*. `"1"` is also a *string*. Just don’t use quotes.

**Comment by AcidScorpion** [comment]
Thank you!
```json
{
    "function": "powerline.segments.common.sys.system_load",
    "args": {
    "threshold_good": 0.3,
    "threshold_bad": 0.5
    },
    "priority": 60
},
```
works!
