### ISSUE TITLE
Powerline consuming lots of CPU and IO under vim

### ISSUE THREAD

**Issue by lukaslueg** [powerline/powerline#1701]
I'm probably barking up the wrong tree here, I couldn't find any more information on how to debug this, though: The setup is MacOS with Vim8 and tmux 2.3 from homebrew and powerline-status 2.5 from PIP. My Vim is being awfully slow if there are many tmux/vim-panes opens.

Turns out the culprit seems to be that Vim causes powerline to be run on every single refresh event (scrolling, typing a single key etc.). Tracing shows that the whole python interpreter and powerline are loaded on every such event, leading to excessive - though cached - I/O and CPU. 

I've no idea wether the source of the problem is within Vim, tmux, powerline or my setup. The powerline-daemon is running, `file $(which powerline)` is the compiled Mach-O and apart from the problem stated above everything is working fine.

Any idea how to approach this situation?

**Comment by ZyX-I** [comment]
Python interpreter should be loaded once per each Vim instance, though do some job on each event (which Vim normally spawns a lot, but only if you do something with it) it should not unload the interpreter, but tmux is different. Without powerline-daemon it should load interpreter on each event, so I would rather check whether powerline is able to connect to the daemon. What exactly do you mean by “tracing shows that the whole python interpreter and powerline are loaded on every such event”? I can understand that python interpreter is loaded from tmux, but in Vim it runs in-process and Vim is unable to unload it.

**Comment by lukaslueg** [comment]
Thanks for the fast reply. I've opened several vim/tmux-panes and start scrolling around in one of the vim-panes. XCode's Instruments file system tracing shows a flood of, in this order

* `tmux` opening /etc/localtime several times
* `tmux` stat'ing a whole bunch of dylibs
* `powerline`stat'ing a whole bunch of dylibs and the config files in `.../powerline/config_files/
* `vim`stat'ing powerline's config files again

The repeats for every keystroke in Vim. After less than ten seconds, I end up with hundrets of I/O-calls.

I was not able to reproduce a reload of the interpreter (so yeah, the env is not fully stable) but I've definitely seen that too.

**Comment by ZyX-I** [comment]
I do not know why somebody is `stat`ing /etc/localtime or dylibs, but config_files are `stat`ed by powerline in order to determine whether they changed. To get rid of statting them you need to do one or both of the following:

- Install `pyuv`: this way it should stop statting config files and use macos fsevents daemon instead.
- Set `config.json/"common"/"interval"` to something non-zero (determines how often configuration changes are checked) or, better, `config.json/"common"/"reload_config"` to false (disables reloading configuration) by creating/editing ~/.config/powerline/config.json.

In both cases you will need to restart Vim and daemon. Restarting daemon is inevitable, in Vim you may use `:python import powerline; powerline.reload(); del powerline` instead (note: officially unstable functionality, but works fine most of time).

**Comment by ZyX-I** [comment]
By the way, `powerline` should not be statting config files, it normally just connects to the daemon and sends it data, then prints to stdout everything received from the daemon. If connection fails it replaces itself with `powerline-render` which will indeed stat the config files.

**Comment by lukaslueg** [comment]
Thanks for the useful info. I've updated my local config files to prevent powerline from re-reading the config files and ensured that the daemon is active. Powerline itself is mostly quite now and the problem seems to stem from Vim causing Tmux to re-render everything on basically every keypress. Closed.
