### ISSUE TITLE
Powerline affects tmux 2.4 CPU usage?

### ISSUE THREAD

**Issue by maotora** [powerline/powerline#1758]
Hello,

I recently updated to `tmux V 2.4` and soon started to notice the huge increase in tmux [CPU usage](https://github.com/tmux/tmux/issues/889). 

Today I set up to get in this and found out when I commented my tmux powerline sourcing line 
`
source "/usr/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"
`
tmux works normally (without eating CPU).

It's probably not helpful but I tried changing my powerline/theme configurations to 
`$ touch empty.json` and reflected that in `~/.config/powerline/config.json` lost theme as expected but tmux ran smoothly.

If I remove every line and keep just the barebones which don't display anything however CPU goes up again.

Like this :- 

```
{
	"segments": {
		"right": [
        ]
	}
}
```
Please help.

**Comment by ZyX-I** [comment]
Are you using powerline-daemon?

**Comment by cryptomilk** [comment]
Same here, I have powerline-daemon running ...

**Comment by maotora** [comment]
@ZyX-I by using powerline-daemon you mean this `run "powerline-daemon -q"` in tmux?

If so, not really.

**Comment by pjcj** [comment]
I see this too, running the daemon.  It appears that the status line is being updated continually, irrespective of the value of status-interval.

My understanding is that the status-interval is the maximum time between status line updates, and that updates happen sooner when certain events trigger them.  My guess is that powerline running is causing such an event meaning that is it run again as soon as it has finished.

**Comment by pjcj** [comment]
And I notice now that the problem only happens with more than one session attached.  I'm still unclear as to whether this is a powerline or tmux bug.

**Comment by ZyX-I** [comment]
I do not actually know which event it may be. Except for the “segments” not managed by powerline (i.e. all those on the left which are present with default theme) it is only using `tmux display -p '#D'` call (2x, for left and right), `#(cmd)` and `cmd` returning a highlighed string without additional (non-highlighting) `#…` tokens. Though it appears now that starting from some tmux version <code>\\"\`tmux display -p '#D'\`\\"</code> could be replaced by simply `#D` because this tmux call in reality is just something like `tmux display -p 239`. Do not know which tmux version that is though.

**Comment by ZyX-I** [comment]
Wondering what if you adjust `status-left` and `status-right` calls with this optimization, does it affect CPU usage?

**Comment by vishwin** [comment]
I'm also noticing this sharply increased CPU usage with two sessions, however one of the sessions needs a maximised window to trigger. Using `powerline-daemon` on `tmux` in `termite` with 3840x2160 resolution and double scaling.

**Comment by pjcj** [comment]
I've looked into this a little further.  I can confirm that the problem only happens when more than one session is attached.

I concentrated on the status-right, by making my status-left a constant.  The right-status is set in ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline_tmux_1.7_plus.conf line 1 as:

set -g status-right '#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id="`tmux display -p "#D"`" --width=`tmux display -p "#{client_width}"` -R width_adjust=`tmux show-options -g status-left-length | cut -d" " -f 2`)'

If I change it to:

set -g status-right '#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id="%36" --width=150 -R width_adjust=`tmux show-options -gv status-left-length`)'

then I get correct behaviour again.  That is, I have expanded the values for pane_id and width.

Leaving either of those values as they are currently set then, appears to trigger the status-line update event.

Could it be that display -p is the culprit?  The status line shouldn't need to be updated if the message goes to stdout.

Using a simple "#D" makes no difference.

**Comment by ZyX-I** [comment]
@pjcj I can’t just put static values there. If replacing calls for tmux with just `#D` worked fine it would be fine, I do not need these calls any longer. But something like `#D` and `#{client_width}` inside `#()` are needed. Can you confirm that without powerline, but with statusline set to just `#(echo #D #{client_width})` cpu usage is higher then normal? If this is true you can reopen tmux bug because this no longer can be viewed as powerline bug.

BTW: a random thought, what if you adjust tmux calls to use `"#"D` and `"#""{client_width}"` instead? I mean, so that inner tmux calls will receive literal `#D` and `#{client_width}`. Because it looks like a tmux bug with processing `#D` or `#{client_width}` inside `#()`, not something to do with `display -p` (based on your “Using a simple "#D" makes no difference.” statement).

**Comment by pjcj** [comment]
I think your random thought is a solution.

In ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline_tmux_1.7_plus.conf I set:
    set -g status-right '#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id="#"D --width=`tmux display -p "#""{client_width}"` -R width_adjust=`tmux show-options -g status-left-length | cut -d" " -f 2`)'

And in ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline_tmux_2.1_plus.conf:
    set -qg status-left "#{?client_prefix,#[fg=$_POWERLINE_SESSION_PREFIX_FG]#[bg=$_POWERLINE_SESSION_PREFIX_BG]#[$_POWERLINE_SESSION_PREFIX_ATTR],#[fg=$_POWERLINE_SESSION_FG]#[bg=$_POWERLINE_SESSION_BG]#[$_POWERLINE_SESSION_ATTR]} #S #{?client_prefix,#[fg=$_POWERLINE_SESSION_PREFIX_BG],#[fg=$_POWERLINE_SESSION_BG]}#[bg=$_POWERLINE_BACKGROUND_BG]#[nobold]$_POWERLINE_LEFT_HARD_DIVIDER#(env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left --width=`tmux display -p '#''{client_width}'` -R width_adjust=`tmux show-options -g status-right-length | cut -d' ' -f2` -R pane_id='#''D')"

(I don't know how to mark up those lines correctly.)

And then, as far as I can tell, everything is working correctly.

I don't have time to look further into things right now, or to produce a minimal test case, but it seems that we have a solution at least.  Perhaps that's sufficient to decide whether the bug lies with powerline or tmux?

**Comment by ZyX-I** [comment]
@pjcj This does not look like a powerline bug, I cannot imagine a good reason for additional tmux call (which would be fork+exec+connecting and writing to the socket, processing on the server, then reading back and passing that via stdout) produce less CPU usage. Though out of all actions only reading and processing are performed on the server (and contribute to visible tmux CPU usage), but everything else should contribute to the total CPU usage.

**Comment by pjcj** [comment]
I agree that this now looks like a tmux bug. I have just now added a minimal test case to the original tmux bug report showing the problem.

**Comment by pjcj** [comment]
And it looks like @nicm has a (as yet unapplied) fix.

**Comment by pjcj** [comment]
This has now been merged to tmux as tmux/tmux@0ccfb61bb0e0beb5fe76b64e30637de7d9f696c7

This ticket can be closed, I think.

**Comment by maotora** [comment]
Thanks @pjcj and @ZyX-I for your help. 🥇 🥇
