### ISSUE TITLE
Updating to master results in error message

### ISSUE THREAD

**Issue by burningTyger** [powerline/powerline#1766]
I'm on Arch wit tmux 2.4 installed and I just upgraded to master

Using powerline with just tmux I do get powerline as my statusline but the left and right side show an error message instead of the segments:

`finish_args() missing 1 required positional argument: 'args'`

This happens even if I use the default settings.

**Comment by ZyX-I** [comment]
How did you upgrade to master? And to which commit exactly?

**Comment by burningTyger** [comment]
`sudo pip install --upgrade git+git://github.com/powerline/powerline` and I'm on `c9824da7016fafa060720cbe26eac601bc5c8947`. Then upgraded to the current commit as well but that didn't help either.

**Comment by ZyX-I** [comment]
Are you sure you have only one powerline installed? It is not uncommon to have powerline installed both for user and system-wide or for different Python version?

**Comment by burningTyger** [comment]
I noticed I have one in a 3.4. directory and one in a 3.5 directory. But then I call just the 3.5 version in my tmux conf. Should I remove one of them or clean up everything and start over again?

**Comment by ZyX-I** [comment]
@burningTyger It is not relevant what you source in tmux conf, from tmux conf tmux will just call `powerline-config` which will use whatever is in $PATH. Since you somehow use wrong by default it is better to remove both, make sure powerline does not work (specifically, `powerline-config` and `powerline` called from shell report unknown command and `python -c 'import powerline'` neither works for any Python version you are using) and reinstall.

**Comment by burningTyger** [comment]
Thank you for your time and patience. It works again. Python is a mystery to me.
