### ISSUE TITLE
vim will stuck when edit a big file.

### ISSUE THREAD

**Issue by dayancn** [powerline/powerline#1768]
when I edit a big file, vim will stuck. when I delete powerline plugin, and edit the file again, it's ok.
My file have 169819 lines.

**Comment by dayancn** [comment]
when change back to the Version: β, it's ok.

**Comment by ZyX-I** [comment]
Powerline does not have version β.

**Comment by ZyX-I** [comment]
You may need to create a different default scheme which does not have trailing whitespace segment (and, maybe, tagbar because I do not know what that is going to do with this file if tagbar is installed). I.e. copy powerline/config_files/themes/vim/default.json to ~/.config/powerline/themes/vim/default.json and remove dictionaries with trailing_whitespace and ….current_tag functions.

**Comment by dayancn** [comment]
Ok, thank you very much.
