### ISSUE TITLE
Sporadic weather error

### ISSUE THREAD

**Issue by yads** [powerline/powerline#1773]
Just upgraded to version 2.6 and I'm getting the following sporadic error:
```
ERROR:tmux:WeatherSegment:Exception while computing state for None: 'NoneType' object is not subscriptable
```

My configuration is pretty simple:
```
{
  {
        "function": "powerline.segments.common.wthr.weather",
        "args": {
          "icons": {
            "day":           "〇",
            "blustery":      "⚑",
            "rainy":         "☔",
            "cloudy":        "☁",
            "snowy":         "❅",
            "stormy":        "☈",
            "foggy":         "≡",
            "sunny":         "☼",
            "night":         "☾",
            "windy":         "☴",
            "not_available": "�",
            "unknown":       "⚠"
          }
        }
      }
}
```

This was working before the upgrade. Seems to have the same issue using Python 2 and Python 3. Also fails with or without the icon configuration.

**Comment by ZyX-I** [comment]
This is because weather service returns invalid response, nothing to do with Python version. Not something I can fix in a way other then “switch to another weather provider”. But I have no idea which would not have one problem or another, if you have some ideas feel free to create a PR (though better not switch, but add ability to select one instead, either via argument (better) or like player segments do (if another weather provider would be too different regarding what `args` it requires)).
