### ISSUE TITLE
Bash error after I execute a command

### ISSUE THREAD

**Issue by abaveja313** [powerline/powerline#1788]
Whenever I execute a command, after the output from it, I get:
`-bash: last_pipe_status: bad array subscript`

Attached  is a screenshot of my interaction
<img width="616" alt="screen shot 2017-06-16 at 4 31 42 pm" src="https://user-images.githubusercontent.com/10778111/27247848-5cfdfe1e-52b1-11e7-8c00-65fef1ecade0.png">

**Comment by ZyX-I** [comment]
You have outdated bash, see #1782. Or update powerline to `develop`.

**Comment by chrischi90** [comment]
I'm getting this error as well even though my iTerm2 is getting bash from 'usr/local/bin/bash' and my bash version is up to date (4.4.12).

<img width="550" alt="screen shot 2017-07-19 at 3 26 54 pm" src="https://user-images.githubusercontent.com/3594661/28386203-cfdc23e2-6c98-11e7-8c75-0331ef3aa2a2.png">

**Comment by ZyX-I** [comment]
@chrischi90 What `bash --version` prints inside an iTerm2 is not an indication of what iTerm2 had run. Interactive bash sources its configuration, *iTerm2 does not source bash configuration*. So if your bash configuration happened to edit $PATH your check is useless. Most\* shells provide `{shell_name}_VERSION` environment variable, bash included, this should be more relevant because unlike `$PATH` `$BASH_VERSION` is normally never changed by the configuration.

\* Of what I have included: zsh, bash, posh, ksh, fish, xonsh. Not included: dash, busybox, tcsh (maybe they just use different convention though, I only checked for `{shell_name}_VERSION`).

**Comment by RamaDL** [comment]
Solution in this thread: [https://github.com/powerline/powerline/pull/1782](url)
I solved the problem upgrading BASH with MacPorts:
sudo port install bash
And changing the absolute path where terminal.app bring the bash executable, I did this enabling Command(full path) on menu Terminal->Preferences->General->Command(full path) and filling de field with:
/opt/local/bin/bash.
