### ISSUE TITLE
Misaligned glyphs from the powerline-fonts

### ISSUE THREAD

**Issue by fpqc** [powerline/powerline#1789]
Hey, I'm on Arch, and I've been using the powerline fonts for a while. Arch moved over to using the fallback fonts by default instead of the patched ones, and I've noticed a consistent persistent misalignment of the glyphs with an number of the supported fonts including but not limited to Source Code Pro.

I've seen this on multiple machines, and I'm not totally sure what is the problem
![screenshot from 2017-06-23 17-35-31](https://user-images.githubusercontent.com/6083371/27501383-ea33d8e2-583a-11e7-8241-cb7dac7882b5.png)

It draws off-alignment in Gnome-Terminal, Tilda, and even suckless st, so i think it's a font problem.

**Comment by ZyX-I** [comment]
There is no solution known to make fallback font correctly aligned given the number of possible setups, this is why patched fonts exist. You already have a good case, do not expect it be better, not without making some other setups worse.

**Comment by fpqc** [comment]
@ZyX-I I checked pretty much all of the fonts that are included in the pre-patched setup (the ones that the powerline tarball has a fontconfig setup for).  All of them had this same offset that leaves a gap on the left and with the glyph ever-so-slightly too high.  I also got the same results with the pre-patched versions.  

I realize that a change might make the glyph look worse on some fonts, but on the supported/recommended ones, a slight nudge left and down will work uniformly.  If you'd like, I can screenshot each of the 'recommended' fonts and demonstrate this.

Thank you for your time and attention!

**Comment by fpqc** [comment]
I mean, the last time the symbol font was recompiled and re-tuned appears to be before freetype 2.7, which completely changed the default renderer.  I'd bet that this is an artifact of that.

**Comment by ZyX-I** [comment]
The “setup” includes the combination of the operating system, the font library, font which is used for fallback and the application using the font library. AFAIR the fallback was already adjusted a few times, including with exactly this error before making it left like this.

And @Lokaltog which was doing the font stuff have already left the project. I personally never did anything to fonts aside from patching terminus which was easy because of it being a bitmap font. I may merge an alternative fallback if somebody fixes it for 2.7 or whatever is causing the problem, but me doing an adjustment will most likely screw the thing up. It is actually hard to determine whether there are people for which fallback looks fine since they have no reason to post here. For me fallback is almost always worse then your case (especially if I do not enable smoothing). Though for 11pt Source Code Pro it appears to be fine, but for 15pt it is like your case.

**Comment by fpqc** [comment]
Alright. I might do some testing and messing about with the symbol font, and if I can get a consistently better result, I'll submit a pull request =].
