### ISSUE TITLE
IPython prompt customization

### ISSUE THREAD

**Issue by i5ar** [powerline/powerline#1838]
By default IPython shows a green prompt for the input and a red prompt for the output.
Is it possible to add something like `prompt_count_out` so it will be easier to add this feature to a custom theme without overriding `config_files/colorschemes/ipython/__main__.json` and `segments/ipython.py`?
There is eventually another way to achieve this? Thank you.

**Comment by ZyX-I** [comment]
No, currently custom highlighting for the same segments within one extension is not supported, a rare exception like the date segment which can be told whether it is a date or time is there for another reason (basically to not have “time” segment which is essentially a copy of “date”). I do not know what is the proper way to add this and whether it is the right thing to add the feature at all (from the architectural point of view), currently same segments have same coloring, with the only exception of listers being able to make prefixed versions (which still would not stop powerline from searching for non-prefixed version if prefixed one is not found).

That can be done on your machine without having to alter any of the repositories files though, there is no reason you can’t just copy `powerline/segments/ipython.py` to any other location with any name you like (including renaming of the inner function) as long as destination is importable and configuration files are user-overridable by design.
