### ISSUE TITLE
powerline-setup throws error on Ubuntu 17.10 using the Fish prompt

### ISSUE THREAD

**Issue by murillow** [powerline/powerline#1850]
I just installed the powerline apt package on Ubuntu 17.10 and followed the documentation to install it for the Fish prompt, then I got the error below after trying to launch Fish. The `{repository_root}` of this ubuntu package is "/usr/share".

```
/usr/share/powerline/bindings/fish/powerline-setup.fish (line 35): function: Illegal function name '--on-variable'
		function --on-variable fish_key_bindings _powerline_set_default_mode
			if test x$fish_key_bindings != xfish_vi_key_bindings
		^
in function “powerline-setup”
	called on line 14 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

/usr/share/powerline/bindings/fish/powerline-setup.fish (line 42): function: Illegal function name '--on-variable'
		function --on-variable POWERLINE_COMMAND _powerline_update
			set -l addargs "--last-exit-code=\$status"
		^
in function “powerline-setup”
	called on line 14 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

/usr/share/powerline/bindings/fish/powerline-setup.fish (line 78): 
		_powerline_set_default_mode
		^
in function “powerline-setup”
	called on line 14 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

/usr/share/powerline/bindings/fish/powerline-setup.fish (line 79): 
		_powerline_update
		^
in function “powerline-setup”
	called on line 14 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup
```

**Comment by ZyX-I** [comment]
This error is long since fixed, fix was in 2.5.1: you need to update. And {repository_root} is not /usr/share in the case, there is no repository to talk about its root, most files are probably in /usr/lib/python2.7/site-packages, some are in /usr/bin, …: no single location.

**Comment by murillow** [comment]
Sorry, I'm using the 2.5-1.1 version. I can't find a fix for this error, can you help?

**Comment by murillow** [comment]
Ok, I had to install powerline both by this ubuntu package and by pip to use with fish and vim for this whole thing to work together. No idea how that error happened but this powerline package is 2.5-1.1.

**Comment by ZyX-I** [comment]
Don’t install two variants of the powerline package, they will go out of sync and you will eventually start seeing errors like #1780.

**Comment by ZyX-I** [comment]
I would suggest to file a bug to where bugs about Ubuntu packages are filed. It should be valid as long as your point is “powerline version from repository is not compatible with fish version”.

**Comment by murillow** [comment]
Ok, I just did that exactly as you said. Let's see what happens.

**Comment by krisavi** [comment]
Same error is with Debian package.

$ ls /usr/lib/python2.7/dist-packages/powerline/bindings/
__init__.py  __init__.pyc  config.py  config.pyc  ipython/  pdb/  tmux/  vim/  wm/  zsh/
$ ls /usr/share/powerline/bindings/
awesome/  bar/  bash/  fish/  i3/  lemonbar/  qtile/  rc/  shell/  tcsh/  tmux/  zsh/

Seems that if I use dist-packages, then fish will not work, due to missing bindings there.
Package should be 2.5-1.1

Only version installed is from 
apt install python-powerline

Error:
`/usr/share/powerline/bindings/fish/powerline-setup.fish (line 35): function: Illegal function name '--on-variable'
                function --on-variable fish_key_bindings _powerline_set_default_mode
                        if test x$fish_key_bindings != xfish_vi_key_bindings
                ^
in function 'powerline-setup'
        called on line 3 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

/usr/share/powerline/bindings/fish/powerline-setup.fish (line 42): function: Illegal function name '--on-variable'
                function --on-variable POWERLINE_COMMAND _powerline_update
                        set -l addargs "--last-exit-code=\$status"
                ^
in function 'powerline-setup'
        called on line 3 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

/usr/share/powerline/bindings/fish/powerline-setup.fish (line 78):
                _powerline_set_default_mode
                ^
in function 'powerline-setup'
        called on line 3 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

/usr/share/powerline/bindings/fish/powerline-setup.fish (line 79):
                _powerline_update
                ^
in function 'powerline-setup'
        called on line 3 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup`


for me the fish.config is:
`set fish_function_path $fish_function_path "/usr/share/powerline/bindings/fish"
powerline-setup`

I believe it might be packaging problem not to put everything in the same location, but that should be still issue in here.
