### ISSUE TITLE
Get wrong width of screen when setting tmux window status on Windows Bash

### ISSUE THREAD

**Issue by 0xddaa** [powerline/powerline#1862]
There are some problems when displaying tmux windows status on Window Bash
As the screenshot, the left side could not display session name and the right side displayed hostname at the next line.
The character for splitting `>` was also abnormal.
I am not sure the reason but I guess the python script get wrong screen width during initializing.

Environment:
 - Windows 10 15063.726
 - Bash 4.4.0-43-Microsoft
 - tmux 2.1
 - powerline-status: 2.6

.tmux.conf:
```
source /usr/share/doc/tmux/examples/vim-keys.conf
source /usr/share/doc/tmux/examples/screen-keys.conf
source /usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/powerline.conf

set-option -g xterm-keys # support arrow
set-option -g default-terminal "screen-256color"
```

.bashrc: default setting in Bash

![171126040446](https://user-images.githubusercontent.com/5286233/33234279-fa14a2de-d25e-11e7-9881-840ba4cbe740.png)

**Comment by ZyX-I** [comment]
Powerline is not what is responsible for placing data on screen, it only tells tmux *what* to place there. Given that `LAPTOP ` is seven characters (there is trailing space) - exactly a number of powerline arrows - it looks like your terminal emulator has miscalculated width of the status line (thinking that powerline characters have double width), while both tmux and font rendering library emulator is using were correct.

In any case, this is not a powerline issue because powerline does not control the empty space in the middle. Powerline controls what tmux shows at the right and, partially, at the left, but actually emitting correct escape sequences and calculating spacing in the middle is tmux responsibility.

You may want to set `default_top_theme` in `~/.config/powerline/config.json`/`"common"` to something like `unicode` to disable powerline arrows.
