### ISSUE TITLE
Q: Does it support git flags?

### ISSUE THREAD

**Issue by Mamad026** [powerline/powerline#1864]
Does powerline support git flags?
I have searched for it but no desired results.
I have already installed it on my Fedora 27 with [this article](https://fedoramagazine.org/add-power-terminal-powerline/) but I don't know how to check it out (git flag support). If it does, How can I check it out?

**Comment by ZyX-I** [comment]
For questions there is a mailing list. Though I have no idea what do you mean by “supporting git flags”, so can’t answer the question.

**Comment by Mamad026** [comment]
Yes there is but there isn't any desired FAQ for my question & I mean the emojies that shown git status & just one more thing,
WHY YOU CLOSED THE ISSUE WHEN YOU DON'T KNOW THE ANSWER? MAYBE SOMEONE KNOW THAT & HELP ME.

**Comment by ZyX-I** [comment]
Because question is not an issue, issue tracker is for bugs or feature requests. I am not going to keep anything else open, this is not a discussion forum. And I did not lock it.

Out of the box it is only possible to get “dirty” vs “non-dirty” state with branch segment coloring, though this feature is disabled by default. No emojis anywhere, in the current state they are more likely to not work properly (= appear to shift next characters out of their cells, not be colored or something else) in the terminal then work, though situation is improving.

**Comment by Mamad026** [comment]
Yes, question is not an issue but I saw many times that people ask question in issue tracker and stick "question" to that issue & I think it would be better if you give a small respon (I mean that "Out of the box..." part in first reply) or at least stick a "question" on this issue & not closing issue when you don't know the answer or sth else...
Thanks anyway.
