### ISSUE TITLE
Arrow alignment not quite correct in lemonbar

### ISSUE THREAD

**Issue by beojan** [powerline/powerline#1884]
See image below.

![image](https://user-images.githubusercontent.com/3727925/36596836-58a51b9c-18a7-11e8-8544-779f75d532aa.png)

**Comment by ZyX-I** [comment]
Fonts are maintained in powerline/fonts repository, and you have not specified what font you are using.

**Comment by beojan** [comment]
I'm using Iosevka. The alignment is correct in tmux with the same font, though.

**Comment by ZyX-I** [comment]
@beojan Then you are hitting the issue with using fallback font (PowerlineSymbols.otf) and different font rendering variants. Even if there is a way to make fallback font look good in all environments (I doubt so) I do not know it, so you will have to patch the font or stop using arrows. Since font is using SIL OFL then the result could be placed to https://github.com/powerline/fonts. Also you may try to convince author to add powerline glyphs to the core font in place of maintaining patched version: some fonts (e.g. terminus I am using) already have powerline glyphs.

Note though that the original author of font patcher is no longer maintaining it and so far nobody proficient enough in fonts stepped in. If font patcher yields font with bugs, if you want to patch manually rather then relying on the font patcher or if you want to create a PR to the font repository I am of no help.

**Comment by beojan** [comment]
It turns out Iosevka already includes Powerline glyphs. It's probably some
slight rendering difference between lemonbar and Konsole.
