### ISSUE TITLE
Shell theme not working for `left` side.

### ISSUE THREAD

**Issue by ssampang** [powerline/powerline#1911]
I have powerline running on an aws machine, and it was working fine as of 2 days ago. I just booted the machine up, and updated Oh-my-zsh after I was prompted to do so, and now my powerline configuration seems to be messed up.

This is how my powerline used to look:
<img width="340" alt="screen shot 2018-05-21 at 12 22 25 pm" src="https://user-images.githubusercontent.com/1335633/40325733-b3790e46-5cf1-11e8-9a72-7c9e715dc0da.png">

This is how it looks now:
<img width="388" alt="screen shot 2018-05-21 at 12 23 45 pm" src="https://user-images.githubusercontent.com/1335633/40325782-d9a2f654-5cf1-11e8-85c0-8dfc33ba9351.png">

I can modify the `right` section of my `powerline/themes/shell/default.json` file and see the changes show up (for example, I can remove the git branch segment) in the shell, but any mods I make to the `left` section doesn't seem to cause any changes. It seems like the `left` side is falling back to the default config, so I'm wondering if there's an issue loading the config somewhere?

Any idea what's going on?

**Comment by ZyX-I** [comment]
Probably oh-my-zsh has installed *its* powerline theme? Ever since powerline was just Vim plugin there were plenty, and even now many people do not want to have Python as a dependency for performance or other reasons. You may check what `echo $PS1` and `echo $RPS1` show, if powerline bindings were sourced correctly and not overwritten afterwards by something you would see something similar, though not entirely the same. I have `${ZPYTHON_POWERLINE_[R]PS1}` (difference in one character) there, but you are unlikely to have zpython installed and without it it would be some long command in `$()`. If one side is using powerline and another is using some powerline-like theme you should spot rather huge differences.

**Comment by ssampang** [comment]
Looks like you're right :) 
```
echo $PS1
%{%f%b%k%}%{%K{black}%}%{%F{default}%} %(!.%{%F{yellow}%}.)centos@%m %{%K{blue}%F{black}%}%{%F{black}%} %~ %{%k%F{blue}%}%{%f%}
echo $RPS1
$("$POWERLINE_COMMAND" $=POWERLINE_COMMAND_ARGS shell right -r .zsh --last-exit-code=$? --last-pipe-status="$pipestatus" --renderer-arg="client_id=$$" --renderer-arg="shortened_path=${(%):-%~}" --jobnum=$_POWERLINE_JOBNUM --renderer-arg="mode=$_POWERLINE_MODE" --renderer-arg="default_mode=$_POWERLINE_DEFAULT_MODE" --width=$(( ${COLUMNS:-$(_powerline_columns_fallback)} - ${ZLE_RPROMPT_INDENT:-1} )))
```
I grepped the oh-my-zsh directory for `powerline` though and I don't see any references to powerline except for the fonts. Could oh-my-zsh still be the cause?

**Comment by ZyX-I** [comment]
@ssampang Theme using powerline arrows does not *have* to be called powerline. I could not answer whether OMZ is the cause, I am not using it and having hard to debug issues arising because OMZ has lots of plugins you did not *choose* to install is just why neither I am going to start using it (unless it is prepackaged and until the first issue or until I feel in mood to copy my zshrc there) nor I saw OMZ receiving good attitude on `#zsh`.

**Comment by ssampang** [comment]
Figured it out! I had the `agnoster` theme enabled with OMZ, and somehow it didn't interfere with my powerline config before but started doing so now. I just had to set my OMZ theme to the empty string and my config was back to normal.
