### ISSUE TITLE
Python error and fix

### ISSUE THREAD

**Issue by scholi** [powerline/powerline#1917]
Hi,
Thank you for your awesome plugin. There is a problem with python3 as some path variable are of type bytes and not of type string. I have created a patch making your script perfectly compatible with python3 and should have no effect on python2 versions.

You can find the patch on my ghist: https://gist.github.com/scholi/3c58256a6d0253e4f6e9fdc88b0181f8

Enjoy and regards

Olivier

EDIT: I should note that I have seen the bug with vim (gvim 8.1 and python 3.6) on a win64 machine, but the only important matter is the python 3.6 and the fact that my .vimrc contains: `let g:pymode_python = 'python3'`

**Comment by ZyX-I** [comment]
All paths that are not coming from configuration *may* be bytes, not str because there is no reason to believe that they are anything, but a mere byte string: path may actually contain anything, but NUL byte on linux regardless of locale, including sequences not valid in UTF-8 while using UTF-8 locale. And it is a bug in Python because according to their own documentation a bunch of functions must accept bytes, but do not, see references in #1876. According to their bug tracker bug was fixed, but I do not know in which version exactly.

**Comment by ZyX-I** [comment]
And win64 is also important matter. AFAIK linux support code does not have this error.
