### ISSUE TITLE
tmux issue: Increase the num of powerline increase every time information updated

### ISSUE THREAD

**Issue by arwtyxouymz** [powerline/powerline#1922]
Hi, I'm using powerline in tmux, but the number of powerline is increase when powerline information is updated.

Ubuntu 16.04
tmux 2.7
Terminal hyper
shell bash

[This is the gif of the powerline](https://gyazo.com/db54a6c5d9935a2228f5926492dc06aa)

Is this a bug?
or any solutions?

**Comment by ZyX-I** [comment]
It is what happens if tmux gets either character width or terminal width wrong (given that you did not have that at the start before powerline actually started it got character width wrong). I am not sure which characters it got wrong exactly, but definitely not powerline arrows (as there are those at the start). You need to tweak your theme so that it would not include offending characters, there is nothing powerline can actually do here as there is no way to query terminal for character width, and even there was it is tmux who should do this in the current circumstances.

Note: by “wrong” I mean “different from how wide terminal thinks characters are”, not necessary actually wrong. Based on the display you have shown you have some characters of which your terminal emulator thinks they are two display cells wide and tmux thinks they are one (so tmux stuffs more spaces and terminal wraps: if that was the other way around you would not get repeating statusline, you would get status line that does not extend to the end of the screen).
