### ISSUE TITLE
stash segment only outputs "ST 3"

### ISSUE THREAD

**Issue by benoitbleuze** [powerline/powerline#1940]
Hi,
I am discovering powerline, and I am quite impressed by it so far, specifically how configurable it is.

However the stash segment does not seem to work for me. The git branch segment works fine for me, but the stash segment always outputs in yellow font "ST 3". What can be the problem here?

Unfortunately I am not knowledgeable enough in the use of the tool to know how best to help you in discovering what I do wrong, or how to determine whether it is a bug. I would be happy to give more details with some guidance.

**Comment by ZyX-I** [comment]
Most likely it is because you do have three stash commits. Depending on the method of applying stash to the working directory you may be left with stash commits hanging around: for example, if I ever used the segment I would have seen `ST 7` on powerline repository because I am only using `git stash apply` and do not mind having those commits hanging in local repository. Check `git stash list` for a list of commits in stash and `git help stash` for other variants of working with stash.

**Comment by benoitbleuze** [comment]
Indeed exactly what you suggested. I looked at 2 repos, and by chance they had both 3 stashes, and it didn't occur to me they could both have that. All good, nothing to see here, move along.

Sorry for wasting your time. Keep on the good work.
