### ISSUE TITLE
$POWERLINE_CONFIG_COMMAND is empty

### ISSUE THREAD

**Issue by binarykitchen** [powerline/powerline#1992]
Where is this important environment variable supposed to be set? It's empty here and thus all my tmux sessions starts with a green bar which is wrong.

Using zprezto and pyenv here.

```
michael-heuberger@infernaldarkness ~ ❯❯❯ echo $POWERLINE_CONFIG_COMMAND

michael-heuberger@infernaldarkness ~ ❯❯❯ which powerline-config
/home/michael-heuberger/.pyenv/shims/powerline-config
```

Any clues? Nowhere in your documentation it is mentioned where that env var should be set. Thanks for any hints.

**Comment by binarykitchen** [comment]
ping @ZyX-I

**Comment by B13rg** [comment]
I Just encountered this issue, it started happening after I compiled and started using tmux version 3.1.
This is what tmux gives as the version:
```
bbyers ~ $ tmux -V
tmux next-3.1
```

The issue is with the function `get_tmux_version(pl)` powerline/bindings/tmux/__init__.py not correctly parsing the tmux version.
Here's the error I see:
```
 bbyers ~ $ powerline-config tmux setup
Traceback (most recent call last):
  File "/home/bbyers/.local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/home/bbyers/.local/lib/python3.5/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/home/bbyers/.local/lib/python3.5/site-packages/powerline/bindings/config.py", line 184, in tmux_setup
    tmux_version = get_tmux_version(pl)
  File "/home/bbyers/.local/lib/python3.5/site-packages/powerline/bindings/tmux/__init__.py", line 84, in get_tmux_version
    return TmuxVersionInfo(int(major), int(minor), suffix)
ValueError: invalid literal for int() with base 10: 'next-3'
```

I'm working on a fix right now to correctly parse the version when this is the case.
