### ISSUE TITLE
Is it possible to change chars used for separators?

### ISSUE THREAD

**Issue by ixti** [powerline/powerline#20]
Hi,

It would be nice if there would be a way to override chars used for separators. That will allow to avoid font patching and use own separators, e.g. "|" instead of less-than arrow and so on. Something similar to vim's `set listchars=...`

**Comment by unacceptable** [comment]
After some searching around in the repo, it appears that this is now stored in this config file:

https://github.com/powerline/powerline/blob/4a8e8b5b0ca4a6a5237ec3eadb6fb9fe8e106a81/powerline/config_files/themes/powerline_terminus.json#L2-L11

This is a decent replacement for dividers IMHO: https://unicode-table.com/en/2771/

```
 robert_jackson1 ❱ ~ ❱ .config ❱ powerline ❱ themes ❱ cat powerline_terminus.json
{
    "dividers": {
        "left": {
            "hard": "❱ ",
            "soft": "❱ "
        },
        "right": {
            "hard": " ❰",
            "soft": " ❰"
        }
    }
}
 robert_jackson1 ❱ ~ ❱ .config ❱ powerline ❱ themes ❱
```

**Comment by voltumna** [comment]
Dear all, how do you know which one is used? I tried all of the files i found and none work
I have installed powerline via 
sudo apt install powerline powerline-fonts
because the other way, via github had issues like it could not find the ' ' command.

I tried to locate all the files that has that some symbols in it for the separator, and changed them all but none worked

![image](https://user-images.githubusercontent.com/1274922/158037919-d42874fe-c296-4d1d-b166-a1b0e11fd576.png)

Any help would be appreciated, I am going mad wasting hours on hours on this

Thanks

Mau

**Comment by voltumna** [comment]
I tried to change ALL the possible config files and still nothing:
![image](https://user-images.githubusercontent.com/1274922/158038115-ccc3a219-3098-4e7f-a7aa-f183e17458ec.png)

I really need help

Thanks

Maurizio
