### ISSUE TITLE
Unable to make the powerline work

### ISSUE THREAD

**Issue by sc-1123** [powerline/powerline#2065]
I uses Vim in windows and using Chocolatey to install it, and powerline didn't work in Vim.
I added `let g:Powerline_symbols = 'fancy'` in `vimrc` file.

**Comment by PH111P** [comment]
In case you're still having this issue, your vim configuration seems to be erroneous: Please try to add the following to your `.vimrc` (instead of the line that you added): 
``` vim
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
```
(Also, please, consult [the documentation](https://powerline.readthedocs.io/en/latest/usage/other.html#vim-statusline) for detailed usage instructions in case you haven't done so.)
