### ISSUE TITLE
fuzzy_time segment prints "o'clock three" instead of "three o'clock"

### ISSUE THREAD

**Issue by doctor-jan** [powerline/powerline#2257]
When using the fuzzy_time option in the time.py segment, at the top of each hour we see, for example,
o'clock three
instead of 
three o'clock

All other times are in the format 'x to three' or 'x past three'. So extra code is needed to detect the 0 minutes times and swap the components around.

**Comment by PH111P** [comment]
Hi @doctor-jan,

Thanks for your report. Indeed, that looks like a bug. There was actually even another bug with the string used for "half-past": x:31 and x:30 were printed as "half past x+1". (With such bugs being unnoticed for this long, I am seriously wondering if anyone is actually using this segment.)

The fix is a little bit different than what you suggested:
- The format argument is now unused.
- Instead, each minute_str now is used as a format string and has an '{hour_str}' field to specify where the hour should be placed.

**Comment by doctor-jan** [comment]
Thanks for your super-speedy fix :-)

This is a much better solution, and it looks like the code is now a bit less complex.
