### ISSUE TITLE
Higher CPU Load

### ISSUE THREAD

**Issue by amadeus** [powerline/powerline#396]
I am running MacVim on OSX 10.8.3 and I am noticing a higher CPU usage when MacVim is just sitting idly with a buffer or two open.

With Powerline, I am seeing around 6-10% CPU usage on the Vim process.

If I disable Powerline with exactly the same buffers open, it's more in the realm of 0-0.1% CPU usage.

My uninitiated armchair analysis would assume it's something to do with #168, but I am not sure.

**Comment by Poorchop** [comment]
I'm still having this issue using the tmux configuration. Prior to touching any of the default configs, powerline's CPU usage was extremely low. I added the weather and external IP plugins, after which I think everything remained fine. Then I tried adding the internal IP plugin (which failed to work even though I have the netifaces module installed). Since internal IP wasn't working, I removed that segment, after which I noticed the high CPU usage.

![untitled](https://cloud.githubusercontent.com/assets/5256208/7552457/05061066-f683-11e4-9246-e05810720a3b.png)

**Comment by ZyX-I** [comment]
@Poorchop Did you restart daemon in process? Removing internal IP segment leaves thread which computes it untouched.

**Comment by Poorchop** [comment]
Yes I have restarted powerline-daemon and I have even rebooted my server multiple times since noticing this issue. A week later, it seems like the CPU usage is even higher than before. This isn't too big of a deal for servers but if people are running this in a local tmux session on a laptop, then it could be sucking up battery. I'll test this on a local machine when I get the chance to see if the results are the same.

**Comment by ZyX-I** [comment]
Can you run powerline daemon with a profiler:

    python -m cProfile -o profile /usr/bin/powerline-daemon -q

and post `profile` file here? I have no idea what may be causing this CPU usage.

And it is better to have another issue. This one is about Vim.
