### ISSUE TITLE
Powerline not working with janus setup

### ISSUE THREAD

**Issue by anthonybrown** [powerline/powerline#670]
I can't seem to get this to work. I am using the janus .vimrc file.

**Comment by Noreaster76** [comment]
@anthonybrown @burningTyger It's been years since your posts, and I have to imagine that you're not still wrestling with this, but for anyone who lands on this page, https://github.com/powerline/powerline/issues/670#issuecomment-32716986 helped me figure it out. I found that by disabling the `syntastic` plugin in janus and also disabling janus' core `statusline` setting, it allowed powerline to finally show up without having to open a second tab.

([How to disable a janus plugin](https://github.com/carlhuda/janus))

**Comment by burningTyger** [comment]
Thank you, @Noreaster76, I completely forgot about this issue since I moved away from janus. Too many useless configurations. Back to plain old vim config I set up for myself with just the basics and no powerline issues so far.
