### ISSUE TITLE
[Archlinux] No powerline symbols in urxvt with tmux

### ISSUE THREAD

**Issue by starlays** [powerline/powerline#684]
Hello.

I've installed the powerline under archlinux using the recommended package that it is indicated in the documentation [1].

After the install I've added to my ~/.tmux.conf the fallowing line:
`source '/usr/share/tmux/powerline.conf'`
The required patched fond are installed from [2] and `fc-list` reports that it is aware of them.

I tried restarting X as instructed in to the documentation but the result is the same:
![2013-10-21_1329x70](https://f.cloud.github.com/assets/634205/1375031/d64cbe84-3a7a-11e3-9990-f944aeb39781.png)

How can I solve this?

Thank you.

[1]  https://aur.archlinux.org/packages/python-powerline-git/
[2]  https://aur.archlinux.org/packages/ttf-dejavusansmono-powerline-git/

**Comment by ti-mo** [comment]
I'm very sorry for necro'ing this issue, but I'm just leaving this here because this is still high up in the search ranks for this particular problem. It doesn't pertain to Powerline specifically, but it might help out some users none the less. *This is not a Powerline issue*

So, apart from having your locale set properly (an obvious one), most of the Urxvt AUR packages I've come across (specifically `rxvt-unicode-patched` and `rxvt-unicode-better-wheel-scrolling`, a must-have IMO) *are compiled without unicode3 support and frills disabled*. I wouldn't be surprised if other distributions used the same compiler flags. Run `urxvt --help 2>&1 | grep options:` to check which options it was built with. Should contain at least `frills`, `unicode3` and optionally `iso14755` if you want to input Unicode characters as well.

In the PKGBUILD under `build()`:

Change
`--disable-frills \`
to
```
--enable-frills \
--enable-unicode3
```

As long as your terminal emulator is compiled without unicode rendering, no amount of configuration will make it display unicode characters. They're being considered 'unnecessary features', but they add negligible overhead to the size of the installed package (~100KB).

Hope this helps!

Sincerely, a fellow terminal lover

**Comment by alerque** [comment]
Thanks @ti-mo, that's the most useful thing to come out of this issue. I've since switched to Termite and am quite happy with it, but just confirmed that does indeed solve that particular URXVT issue on one system that wasn't fixed by just the locale fix.

**Comment by ti-mo** [comment]
Hey @alerque , happy that solved it for you too! Made a PR to add this to the docs, so hopefully it's a thing of the past for good.

**Comment by rogervs** [comment]
@ti-mo Thanks man, you saved me from wasting another day on trying to get this right in Xterm!!! Definitely owe you a beer ( or 6!)

**Comment by kfrz** [comment]
I'm on `Debian 4.9.2-2` with the following urxvt: 

```rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```

I'm seeing squares where I should be seeing symbols in my oh-my-zsh line ie. 
`/usr/local/src/filedir on master [?] via 💎 `

**Comment by hanss314** [comment]
@kfrz I'm getting the same issue. unicode3 and frills are enabled but I'm getting rectangles instead of arrows. Arch linux, i3 and urxvt

**Comment by hanss314** [comment]
I found a solution that worked for me. I just had to install the fonts from here. https://github.com/powerline/fonts

**Comment by kparikh1** [comment]
I am having this same problem. The closest i have come to solving it is that my i3 window manager is launching the applications with its default encoding set to C. Which does not have the powerline symbols. My regular environment is set to utf8. This means that if I launch urxvt from another terminal application and define the font, it will contain the powerline symbols. I am not sure how to change the default encoding for i3 to utf8.

**Comment by ZyX-I** [comment]
@kparikh1 Based on what I know i3 has nothing to do with defining locale, it will use whatever locale it was launched with. You need to configure whatever runs i3.

**Comment by ZyX-I** [comment]
At least, I am using i3 and I do not have the issue. But I am running that “manually” from `<C-A-F1>` terminal which already has proper locale, not using any kind of automatic X startup or things like gdm as configuring them would be a useless waste of time. Proper locale in that terminal is coming from /etc/env.d/99locale sourced through /etc/profile.env (`env-update` merges all files from /etc/env.d there) sourced by /etc/zsh/zprofile, you distribution should have similar mechanizm which maybe will apply to whatever you use to run i3.

**Comment by Awan** [comment]
![foo](https://user-images.githubusercontent.com/42554663/62264531-b556a200-b439-11e9-9d65-23ba66d9d9a2.png)


I'll post the .Xresources here, https://github.com/Awan/cfg.git or https://gitlab.com/Abdullah/cfg.git
