### ISSUE TITLE
Can't enable weather segment

### ISSUE THREAD

**Issue by fofobofo** [powerline/powerline#779]
I'm trying to enable weather segment but with no success. I added this code

``` json
{
    "name": "weather",
    "priority": 50,
    "args": {
        "unit": "F",
        "location_query": "oslo, norway"
    }
}
```

at the end of my theme file. When I start MacVim I get an error

Error detected while processing VimEnter Auto commands for "*":
2014-01-30 14:13:11,122:ERROR:vim:segment_generator:Failed to generate segment from {u'priority': 50, u'args': {u'location_query': u'oslo, norway', u'u
nit': u'F'}, u'name': u'weather'}: 'module' object has no attribute 'weather'

I've read powerline documentation but I'm still confused. Any help will be appreciated.

**Comment by niltonvasques** [comment]
Hey, I have the same problem! I can't get weather segment works properly. 
This is my theme file:
{
    "segments": {
        "right": [
            {
                "function": "powerline.segments.common.players.cmus",
                "name": "player",
                "args": {
                    "format": "{state_symbol} {title} - {artist} - {album}"
                }
            },
            {
                "function": "powerline.segments.common.time.date",
                "args": {
                    "format": "%d/%m/%y"
                }
            },
            {
                "function": "powerline.segments.common.time.date",
                "name": "time",
                "args": {
                    "format": "%H:%M",
                    "istime": true
                }
            },
            {
                "function": "powerline.segments.common.wthr",
                "module": "powerline.segments.common",
                "name": "weather",
                "args": {
                    "unit": "C",
                    "location_query": "oslo, norway"
                }
            },
            {
                "function": "powerline.segments.common.net.hostname"
            }
        ]
    }
}

**Comment by ZyX-I** [comment]
@niltonvasques You don’t have weather segment there:

1. `powerline.segments.common.wthr` is a module name, *not* function name.
2. You must put module name *and* function name in `function` key.
3. `name` key specifies *segment* name and it is better not to use it. This name no longer has anything to do with segment function.
4. It is highly suggested to run `powerline-lint` prior to reporting anything here. At least you would be able to report error in powerline-lint (usual encoding problem: error message that should’ve told you about `wthr` from module `powerline.segments.common` not being callable instead emits a UnicodeEncodeError).
5. It is not the same problem. More, since the time this issue was reported specification of configuration changed significantly (AFAIR this issue was reported before release). Do not write any new issues to the closed issue, *especially* with INVALID status (if you feel your issue is the same better write to the mailing list because most likely it means that you have error in *your* configuration which is not a powerline issue).
